// Date: 26.01.2016 16:09:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMiniNuke extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
  
  public ModelMiniNuke()
  {
    this.textureWidth = 64;
    this.textureHeight = 32;
    
      this.Shape1 = new ModelRenderer(this, 0, 0);
      this.Shape1.addBox(0F, 0F, 0F, 5, 4, 2);
      this.Shape1.setRotationPoint(-2F, -2F, -1F);
      this.Shape1.setTextureSize(64, 32);
      this.Shape1.mirror = true;
      setRotation(this.Shape1, 0F, 0F, 0F);
      this.Shape2 = new ModelRenderer(this, 0, 6);
      this.Shape2.addBox(0F, 0F, 0F, 5, 2, 4);
      this.Shape2.setRotationPoint(-2F, -1F, -2F);
      this.Shape2.setTextureSize(64, 32);
      this.Shape2.mirror = true;
      setRotation(this.Shape2, 0F, 0F, 0F);
      this.Shape3 = new ModelRenderer(this, 58, 0);
      this.Shape3.addBox(0F, 0F, 0F, 1, 2, 2);
      this.Shape3.setRotationPoint(-3F, -1F, -1F);
      this.Shape3.setTextureSize(64, 32);
      this.Shape3.mirror = true;
      setRotation(this.Shape3, 0F, 0F, 0F);
      this.Shape4 = new ModelRenderer(this, 52, 0);
      this.Shape4.addBox(0F, 0F, 0F, 1, 2, 2);
      this.Shape4.setRotationPoint(3F, -1F, -1F);
      this.Shape4.setTextureSize(64, 32);
      this.Shape4.mirror = true;
      setRotation(this.Shape4, 0F, 0F, 0F);
      this.Shape5 = new ModelRenderer(this, 46, 0);
      this.Shape5.addBox(0F, 0F, 0F, 2, 2, 1);
      this.Shape5.setRotationPoint(4F, -1F, -2F);
      this.Shape5.setTextureSize(64, 32);
      this.Shape5.mirror = true;
      setRotation(this.Shape5, 0F, 0F, 0F);
      this.Shape6 = new ModelRenderer(this, 40, 0);
      this.Shape6.addBox(0F, 0F, 0F, 2, 2, 1);
      this.Shape6.setRotationPoint(4F, -1F, 1F);
      this.Shape6.setTextureSize(64, 32);
      this.Shape6.mirror = true;
      setRotation(this.Shape6, 0F, 0F, 0F);
      this.Shape7 = new ModelRenderer(this, 24, 0);
      this.Shape7.addBox(0F, 0F, 0F, 2, 1, 2);
      this.Shape7.setRotationPoint(4F, -2F, -1F);
      this.Shape7.setTextureSize(64, 32);
      this.Shape7.mirror = true;
      setRotation(this.Shape7, 0F, 0F, 0F);
      this.Shape8 = new ModelRenderer(this, 32, 0);
      this.Shape8.addBox(0F, 0F, 0F, 2, 1, 2);
      this.Shape8.setRotationPoint(4F, 1F, -1F);
      this.Shape8.setTextureSize(64, 32);
      this.Shape8.mirror = true;
      setRotation(this.Shape8, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.Shape1.render(f5);
    this.Shape2.render(f5);
    this.Shape3.render(f5);
    this.Shape4.render(f5);
    this.Shape5.render(f5);
    this.Shape6.render(f5);
    this.Shape7.render(f5);
    this.Shape8.render(f5);
  }
  
  public void renderAll(float f5)
  {
    this.Shape1.render(f5);
    this.Shape2.render(f5);
    this.Shape3.render(f5);
    this.Shape4.render(f5);
    this.Shape5.render(f5);
    this.Shape6.render(f5);
    this.Shape7.render(f5);
    this.Shape8.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
