// Date: 20.02.2019 22:40:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPanzerschreck extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;

	public ModelPanzerschreck() {
		this.textureWidth = 128;
		this.textureHeight = 32;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 40, 2, 3);
		this.Shape1.setRotationPoint(-20F, 0F, -1.5F);
		this.Shape1.setTextureSize(128, 32);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 5);
		this.Shape2.addBox(0F, 0F, 0F, 40, 3, 2);
		this.Shape2.setRotationPoint(-20F, -0.5F, -1F);
		this.Shape2.setTextureSize(128, 32);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 10);
		this.Shape3.addBox(0F, 0F, 0F, 2, 3, 1);
		this.Shape3.setRotationPoint(-7.5F, 2.5F, -0.5F);
		this.Shape3.setTextureSize(128, 32);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 6, 10);
		this.Shape4.addBox(0F, 0F, 0F, 6, 1, 1);
		this.Shape4.setRotationPoint(-7.5F, 5.5F, -0.5F);
		this.Shape4.setTextureSize(128, 32);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 14);
		this.Shape5.addBox(0F, 0F, 0F, 2, 3, 1);
		this.Shape5.setRotationPoint(-1.5F, 2.5F, -0.5F);
		this.Shape5.setTextureSize(128, 32);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 6, 12);
		this.Shape6.addBox(0F, 0F, 0F, 1, 3, 1);
		this.Shape6.setRotationPoint(0.5F, 2.5F, -0.5F);
		this.Shape6.setTextureSize(128, 32);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 10, 12);
		this.Shape7.addBox(-1F, 0F, 0F, 1, 2, 1);
		this.Shape7.setRotationPoint(-2F, 2.5F, -0.5F);
		this.Shape7.setTextureSize(128, 32);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0.3490659F);
		this.Shape8 = new ModelRenderer(this, 0, 18);
		this.Shape8.addBox(0F, 0F, 0F, 1, 4, 4);
		this.Shape8.setRotationPoint(22F, -1F, -2F);
		this.Shape8.setTextureSize(128, 32);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
		this.Shape9 = new ModelRenderer(this, 20, 10);
		this.Shape9.addBox(-3F, 0F, 0F, 3, 1, 1);
		this.Shape9.setRotationPoint(22F, -1F, -0.5F);
		this.Shape9.setTextureSize(128, 32);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, 0F, -0.2617994F);
		this.Shape10 = new ModelRenderer(this, 14, 12);
		this.Shape10.addBox(-3F, 0F, 0F, 3, 1, 1);
		this.Shape10.setRotationPoint(22F, 0.5F, -2F);
		this.Shape10.setTextureSize(128, 32);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, 0F, 0.2617994F, 0F);
		this.Shape11 = new ModelRenderer(this, 14, 14);
		this.Shape11.addBox(-3F, 0F, -1F, 3, 1, 1);
		this.Shape11.setRotationPoint(22F, 0.5F, 2F);
		this.Shape11.setTextureSize(128, 32);
		this.Shape11.mirror = true;
		setRotation(this.Shape11, 0F, -0.2617994F, 0F);
		this.Shape12 = new ModelRenderer(this, 28, 10);
		this.Shape12.addBox(-3F, -1F, 0F, 3, 1, 1);
		this.Shape12.setRotationPoint(22F, 3F, -0.5F);
		this.Shape12.setTextureSize(128, 32);
		this.Shape12.mirror = true;
		setRotation(this.Shape12, 0F, 0F, 0.2617994F);
		this.Shape13 = new ModelRenderer(this, 22, 12);
		this.Shape13.addBox(0F, 0F, 0F, 1, 1, 3);
		this.Shape13.setRotationPoint(-20F, -1.5F, -1.5F);
		this.Shape13.setTextureSize(128, 32);
		this.Shape13.mirror = true;
		setRotation(this.Shape13, 0F, 0F, 0F);
		this.Shape14 = new ModelRenderer(this, 30, 12);
		this.Shape14.addBox(0F, 0F, 0F, 1, 1, 3);
		this.Shape14.setRotationPoint(-20F, -2.5F, -1.5F);
		this.Shape14.setTextureSize(128, 32);
		this.Shape14.mirror = true;
		setRotation(this.Shape14, 0F, 0F, 0F);
		this.Shape15 = new ModelRenderer(this, 36, 10);
		this.Shape15.addBox(0F, 0F, 0F, 3, 1, 1);
		this.Shape15.setRotationPoint(15F, -1F, -2F);
		this.Shape15.setTextureSize(128, 32);
		this.Shape15.mirror = true;
		setRotation(this.Shape15, 0F, 0F, 0F);
		this.Shape16 = new ModelRenderer(this, 108, 10);
		this.Shape16.addBox(0F, 0F, 0F, 0, 12, 10);
		this.Shape16.setRotationPoint(-10F, -5F, -8.5F);
		this.Shape16.setTextureSize(128, 32);
		this.Shape16.mirror = true;
		setRotation(this.Shape16, 0F, 0F, 0F);
		this.Shape17 = new ModelRenderer(this, 38, 12);
		this.Shape17.addBox(0F, 0F, 0F, 1, 3, 1);
		this.Shape17.setRotationPoint(3.5F, 2.5F, -0.5F);
		this.Shape17.setTextureSize(128, 32);
		this.Shape17.mirror = true;
		setRotation(this.Shape17, 0F, 0F, -0.4363323F);
		this.Shape18 = new ModelRenderer(this, 10, 15);
		this.Shape18.addBox(0F, 0F, 0F, 1, 3, 1);
		this.Shape18.setRotationPoint(5F, 2.5F, -0.5F);
		this.Shape18.setTextureSize(128, 32);
		this.Shape18.mirror = true;
		setRotation(this.Shape18, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
		this.Shape16.render(f5);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
