// Date: 29.08.2016 12:31:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMP extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;
	ModelRenderer Shape24;
	ModelRenderer Shape25;

	public ModelMP() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 3, 6, 1);
		this.Shape1.setRotationPoint(-25F, -3F, -2F);
		this.Shape1.setTextureSize(128, 64);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 8, 0);
		this.Shape2.addBox(0F, 0F, 0F, 3, 6, 1);
		this.Shape2.setRotationPoint(-25F, -3F, 2F);
		this.Shape2.setTextureSize(128, 64);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 8);
		this.Shape3.addBox(0F, 0F, 0F, 2, 3, 3);
		this.Shape3.setRotationPoint(-24F, 0F, -1F);
		this.Shape3.setTextureSize(128, 64);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 0, 14);
		this.Shape4.addBox(0F, 0F, 0F, 20, 3, 1);
		this.Shape4.setRotationPoint(-22F, -3F, -2F);
		this.Shape4.setTextureSize(128, 64);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 18);
		this.Shape5.addBox(0F, 0F, 0F, 20, 3, 1);
		this.Shape5.setRotationPoint(-22F, -3F, 2F);
		this.Shape5.setTextureSize(128, 64);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 0, 22);
		this.Shape6.addBox(0F, 0F, 0F, 24, 1, 3);
		this.Shape6.setRotationPoint(-24F, -1F, -1F);
		this.Shape6.setTextureSize(128, 64);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 0, 26);
		this.Shape7.addBox(0F, 0F, 0F, 26, 4, 5);
		this.Shape7.setRotationPoint(-25F, 3F, -2F);
		this.Shape7.setTextureSize(128, 64);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0F);
		this.Shape8 = new ModelRenderer(this, 16, 0);
		this.Shape8.addBox(0F, 0F, 0F, 3, 6, 1);
		this.Shape8.setRotationPoint(-2F, -3F, -2F);
		this.Shape8.setTextureSize(128, 64);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
		this.Shape9 = new ModelRenderer(this, 24, 0);
		this.Shape9.addBox(0F, 0F, 0F, 3, 6, 1);
		this.Shape9.setRotationPoint(-2F, -3F, 2F);
		this.Shape9.setTextureSize(128, 64);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, 0F, 0F);
		this.Shape10 = new ModelRenderer(this, 90, 22);
		this.Shape10.addBox(0F, 0F, 0F, 11, 3, 3);
		this.Shape10.setRotationPoint(-2F, 0F, -1F);
		this.Shape10.setTextureSize(128, 64);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, 0F, 0F, 0F);
		this.Shape11 = new ModelRenderer(this, 19, 38);
		this.Shape11.addBox(0F, 0F, 0F, 26, 1, 4);
		this.Shape11.setRotationPoint(-25F, 7F, -1.5F);
		this.Shape11.setTextureSize(128, 64);
		this.Shape11.mirror = true;
		setRotation(this.Shape11, 0F, 0F, 0F);
		this.Shape12 = new ModelRenderer(this, 78, 35);
		this.Shape12.addBox(0F, 0F, 0F, 20, 5, 5);
		this.Shape12.setRotationPoint(-25F, 8F, -2F);
		this.Shape12.setTextureSize(128, 64);
		this.Shape12.mirror = true;
		setRotation(this.Shape12, 0F, 0F, 0F);
		this.Shape13 = new ModelRenderer(this, 54, 45);
		this.Shape13.addBox(0F, 0F, 0F, 32, 2, 5);
		this.Shape13.setRotationPoint(-5F, 8F, -2F);
		this.Shape13.setTextureSize(128, 64);
		this.Shape13.mirror = true;
		setRotation(this.Shape13, 0F, 0F, 0F);
		this.Shape14 = new ModelRenderer(this, 108, 28);
		this.Shape14.addBox(0F, -6F, 0F, 8, 6, 1);
		this.Shape14.setRotationPoint(1F, 8F, -2F);
		this.Shape14.setTextureSize(128, 64);
		this.Shape14.mirror = true;
		setRotation(this.Shape14, -0.0872665F, 0F, 0F);
		this.Shape15 = new ModelRenderer(this, 84, 52);
		this.Shape15.addBox(0F, 0F, 0F, 18, 9, 3);
		this.Shape15.setRotationPoint(9F, -1F, -1F);
		this.Shape15.setTextureSize(128, 64);
		this.Shape15.mirror = true;
		setRotation(this.Shape15, 0F, 0F, 0F);
		this.Shape16 = new ModelRenderer(this, 0, 43);
		this.Shape16.addBox(0F, -9F, 0F, 18, 9, 1);
		this.Shape16.setRotationPoint(9F, 8F, -2F);
		this.Shape16.setTextureSize(128, 64);
		this.Shape16.mirror = true;
		setRotation(this.Shape16, -0.0872665F, 0F, 0F);
		this.Shape17 = new ModelRenderer(this, 90, 28);
		this.Shape17.addBox(0F, -6F, -1F, 8, 6, 1);
		this.Shape17.setRotationPoint(1F, 8F, 3F);
		this.Shape17.setTextureSize(128, 64);
		this.Shape17.mirror = true;
		setRotation(this.Shape17, 0.0872665F, 0F, 0F);
		this.Shape18 = new ModelRenderer(this, 46, 54);
		this.Shape18.addBox(0F, -9F, -1F, 18, 9, 1);
		this.Shape18.setRotationPoint(9F, 8F, 3F);
		this.Shape18.setTextureSize(128, 64);
		this.Shape18.mirror = true;
		setRotation(this.Shape18, 0.0872665F, 0F, 0F);
		this.Shape19 = new ModelRenderer(this, 0, 35);
		this.Shape19.addBox(0F, -3F, 0F, 4, 3, 5);
		this.Shape19.setRotationPoint(-5F, 13F, -2F);
		this.Shape19.setTextureSize(128, 64);
		this.Shape19.mirror = true;
		setRotation(this.Shape19, 0F, 0F, -0.8726646F);
		this.Shape20 = new ModelRenderer(this, 0, 53);
		this.Shape20.addBox(0F, 0F, 0F, 18, 6, 5);
		this.Shape20.setRotationPoint(9F, 10F, -2F);
		this.Shape20.setTextureSize(128, 64);
		this.Shape20.mirror = true;
		setRotation(this.Shape20, 0F, 0F, 0F);
		this.Shape21 = new ModelRenderer(this, 42, 16);
		this.Shape21.addBox(0F, 0F, 0F, 3, 5, 1);
		this.Shape21.setRotationPoint(1F, 10F, 0F);
		this.Shape21.setTextureSize(128, 64);
		this.Shape21.mirror = true;
		setRotation(this.Shape21, 0F, 0F, 0F);
		this.Shape22 = new ModelRenderer(this, 62, 27);
		this.Shape22.addBox(0F, 0F, 0F, 11, 1, 3);
		this.Shape22.setRotationPoint(-2F, 15F, -1F);
		this.Shape22.setTextureSize(128, 64);
		this.Shape22.mirror = true;
		setRotation(this.Shape22, 0F, 0F, 0F);
		this.Shape23 = new ModelRenderer(this, 62, 31);
		this.Shape23.addBox(-6F, -1F, 0F, 6, 1, 3);
		this.Shape23.setRotationPoint(-2F, 16F, -1F);
		this.Shape23.setTextureSize(128, 64);
		this.Shape23.mirror = true;
		setRotation(this.Shape23, 0F, 0F, 0.5235988F);
		this.Shape24 = new ModelRenderer(this, 20, 10);
		this.Shape24.addBox(0F, 0F, 0F, 2, 1, 3);
		this.Shape24.setRotationPoint(-21F, -2F, -1F);
		this.Shape24.setTextureSize(128, 64);
		this.Shape24.mirror = true;
		setRotation(this.Shape24, 0F, 0F, 0F);
		this.Shape25 = new ModelRenderer(this, 10, 10);
		this.Shape25.addBox(0F, 0F, 0F, 2, 1, 3);
		this.Shape25.setRotationPoint(-5F, -2F, -1F);
		this.Shape25.setTextureSize(128, 64);
		this.Shape25.mirror = true;
		setRotation(this.Shape25, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		this.Shape16.render(f5);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		this.Shape19.render(f5);
		this.Shape20.render(f5);
		this.Shape21.render(f5);
		this.Shape22.render(f5);
		this.Shape23.render(f5);
		this.Shape24.render(f5);
		this.Shape25.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
