// Date: 26.01.2016 14:54:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import com.hbm.items.weapon.ItemGunBase;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.item.ItemStack;

public class ModelFatman extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;
	ModelRenderer Shape24;
	ModelRenderer Shape25;
	ModelRenderer Shape26;
	ModelRenderer Shape27;
	ModelRenderer Shape28;
	ModelRenderer Shape29;
	ModelRenderer Shape30;
	ModelRenderer Shape31;
	ModelRenderer Shape32;
	ModelRenderer Shape33;

	public ModelFatman() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 40, 2, 4);
		this.Shape1.setRotationPoint(-20F, 0F, 0F);
		this.Shape1.setTextureSize(128, 64);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 6);
		this.Shape2.addBox(0F, 0F, 0F, 6, 2, 2);
		this.Shape2.setRotationPoint(-19F, 2F, 1F);
		this.Shape2.setTextureSize(128, 64);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 10);
		this.Shape3.addBox(0F, 0F, 0F, 1, 4, 1);
		this.Shape3.setRotationPoint(-12F, 2F, 1.5F);
		this.Shape3.setTextureSize(128, 64);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 16, 6);
		this.Shape4.addBox(0F, 0F, 0F, 6, 1, 4);
		this.Shape4.setRotationPoint(-10F, 2F, 0F);
		this.Shape4.setTextureSize(128, 64);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 15);
		this.Shape5.addBox(0F, 0F, 0F, 2, 3, 1);
		this.Shape5.setRotationPoint(-7F, 3F, 1.5F);
		this.Shape5.setTextureSize(128, 64);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 4, 10);
		this.Shape6.addBox(0F, 0F, 0F, 3, 3, 1);
		this.Shape6.setRotationPoint(-10F, 3F, 1.5F);
		this.Shape6.setTextureSize(128, 64);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 12, 10);
		this.Shape7.addBox(-1F, 0F, 0F, 1, 2, 1);
		this.Shape7.setRotationPoint(-7F, 3F, 1.5F);
		this.Shape7.setTextureSize(128, 64);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0.5235988F);
		this.Shape8 = new ModelRenderer(this, 36, 6);
		this.Shape8.addBox(0F, 0F, 0F, 10, 1, 4);
		this.Shape8.setRotationPoint(-3F, 2F, 0F);
		this.Shape8.setTextureSize(128, 64);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
		this.Shape9 = new ModelRenderer(this, 64, 6);
		this.Shape9.addBox(0F, 0F, 0F, 2, 3, 2);
		this.Shape9.setRotationPoint(7F, 2F, 1F);
		this.Shape9.setTextureSize(128, 64);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, 0F, 0F);
		this.Shape10 = new ModelRenderer(this, 88, 0);
		this.Shape10.addBox(0F, 0F, 0F, 3, 4, 4);
		this.Shape10.setRotationPoint(17F, -4F, 0F);
		this.Shape10.setTextureSize(128, 64);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, 0F, 0F, 0F);
		this.Shape11 = new ModelRenderer(this, 72, 6);
		this.Shape11.addBox(0F, 0F, 0F, 2, 3, 1);
		this.Shape11.setRotationPoint(18F, -7F, 0F);
		this.Shape11.setTextureSize(128, 64);
		this.Shape11.mirror = true;
		setRotation(this.Shape11, 0F, 0F, 0F);
		this.Shape12 = new ModelRenderer(this, 78, 6);
		this.Shape12.addBox(0F, 0F, 0F, 2, 3, 1);
		this.Shape12.setRotationPoint(18F, -7F, 3F);
		this.Shape12.setTextureSize(128, 64);
		this.Shape12.mirror = true;
		setRotation(this.Shape12, 0F, 0F, 0F);
		this.Shape13 = new ModelRenderer(this, 0, 19);
		this.Shape13.addBox(0F, -4F, 0F, 22, 4, 0);
		this.Shape13.setRotationPoint(-17F, 0F, 1F);
		this.Shape13.setTextureSize(128, 64);
		this.Shape13.mirror = true;
		setRotation(this.Shape13, 0.4363323F, 0F, 0F);
		this.Shape14 = new ModelRenderer(this, 16, 11);
		this.Shape14.addBox(0F, 0F, 0F, 33, 1, 1);
		this.Shape14.setRotationPoint(-17F, -4F, -1F);
		this.Shape14.setTextureSize(128, 64);
		this.Shape14.mirror = true;
		setRotation(this.Shape14, 0F, 0F, 0F);
		this.Shape15 = new ModelRenderer(this, 0, 23);
		this.Shape15.addBox(0F, -4F, 0F, 22, 4, 0);
		this.Shape15.setRotationPoint(-17F, 0F, 3F);
		this.Shape15.setTextureSize(128, 64);
		this.Shape15.mirror = true;
		setRotation(this.Shape15, -0.4363323F, 0F, 0F);
		this.Shape16 = new ModelRenderer(this, 16, 13);
		this.Shape16.addBox(0F, 0F, 0F, 33, 1, 1);
		this.Shape16.setRotationPoint(-17F, -4F, 4F);
		this.Shape16.setTextureSize(128, 64);
		this.Shape16.mirror = true;
		setRotation(this.Shape16, 0F, 0F, 0F);
		this.Shape17 = new ModelRenderer(this, 44, 25);
		this.Shape17.addBox(0F, -4F, 0F, 8, 4, 0);
		this.Shape17.setRotationPoint(8F, 0F, 1F);
		this.Shape17.setTextureSize(128, 64);
		this.Shape17.mirror = true;
		setRotation(this.Shape17, 0.4363323F, 0F, 0F);
		this.Shape18 = new ModelRenderer(this, 44, 21);
		this.Shape18.addBox(0F, -4F, 0F, 8, 4, 0);
		this.Shape18.setRotationPoint(8F, 0F, 3F);
		this.Shape18.setTextureSize(128, 64);
		this.Shape18.mirror = true;
		setRotation(this.Shape18, -0.4363323F, 0F, 0F);
		this.Shape19 = new ModelRenderer(this, 0, 37);
		this.Shape19.addBox(0F, 0F, 0F, 5, 4, 2);
		this.Shape19.setRotationPoint(5F, -6F, 1F);
		this.Shape19.setTextureSize(128, 64);
		this.Shape19.mirror = true;
		setRotation(this.Shape19, 0F, 0F, 0F);
		this.Shape20 = new ModelRenderer(this, 0, 31);
		this.Shape20.addBox(0F, 0F, 0F, 5, 2, 4);
		this.Shape20.setRotationPoint(5F, -5F, 0F);
		this.Shape20.setTextureSize(128, 64);
		this.Shape20.mirror = true;
		setRotation(this.Shape20, 0F, 0F, 0F);
		this.Shape21 = new ModelRenderer(this, 0, 27);
		this.Shape21.addBox(0F, 0F, 0F, 1, 2, 2);
		this.Shape21.setRotationPoint(4F, -5F, 1F);
		this.Shape21.setTextureSize(128, 64);
		this.Shape21.mirror = true;
		setRotation(this.Shape21, 0F, 0F, 0F);
		this.Shape22 = new ModelRenderer(this, 6, 27);
		this.Shape22.addBox(0F, 0F, 0F, 1, 2, 2);
		this.Shape22.setRotationPoint(10F, -5F, 1F);
		this.Shape22.setTextureSize(128, 64);
		this.Shape22.mirror = true;
		setRotation(this.Shape22, 0F, 0F, 0F);
		this.Shape23 = new ModelRenderer(this, 8, 43);
		this.Shape23.addBox(0F, 0F, 0F, 2, 2, 1);
		this.Shape23.setRotationPoint(11F, -5F, 0F);
		this.Shape23.setTextureSize(128, 64);
		this.Shape23.mirror = true;
		setRotation(this.Shape23, 0F, 0F, 0F);
		this.Shape24 = new ModelRenderer(this, 8, 46);
		this.Shape24.addBox(0F, 0F, 0F, 2, 2, 1);
		this.Shape24.setRotationPoint(11F, -5F, 3F);
		this.Shape24.setTextureSize(128, 64);
		this.Shape24.mirror = true;
		setRotation(this.Shape24, 0F, 0F, 0F);
		this.Shape25 = new ModelRenderer(this, 0, 43);
		this.Shape25.addBox(0F, 0F, 0F, 2, 1, 2);
		this.Shape25.setRotationPoint(11F, -6F, 1F);
		this.Shape25.setTextureSize(128, 64);
		this.Shape25.mirror = true;
		setRotation(this.Shape25, 0F, 0F, 0F);
		this.Shape26 = new ModelRenderer(this, 0, 46);
		this.Shape26.addBox(0F, 0F, 0F, 2, 1, 2);
		this.Shape26.setRotationPoint(11F, -3F, 1F);
		this.Shape26.setTextureSize(128, 64);
		this.Shape26.mirror = true;
		setRotation(this.Shape26, 0F, 0F, 0F);
		this.Shape27 = new ModelRenderer(this, 18, 27);
		this.Shape27.addBox(0F, 0F, 0F, 2, 5, 1);
		this.Shape27.setRotationPoint(13F, -5F, 1.5F);
		this.Shape27.setTextureSize(128, 64);
		this.Shape27.mirror = true;
		setRotation(this.Shape27, 0F, 0F, 0F);
		this.Shape28 = new ModelRenderer(this, 84, 6);
		this.Shape28.addBox(0F, 0F, 0F, 1, 3, 1);
		this.Shape28.setRotationPoint(16F, -3F, 1.5F);
		this.Shape28.setTextureSize(128, 64);
		this.Shape28.mirror = true;
		setRotation(this.Shape28, 0F, 0F, 0F);
		this.Shape29 = new ModelRenderer(this, 6, 15);
		this.Shape29.addBox(0F, 0F, 0F, 10, 2, 2);
		this.Shape29.setRotationPoint(3F, -2F, 1F);
		this.Shape29.setTextureSize(128, 64);
		this.Shape29.mirror = true;
		setRotation(this.Shape29, 0F, 0F, 0F);
		this.Shape30 = new ModelRenderer(this, 30, 15);
		this.Shape30.addBox(0F, 0F, 0F, 12, 2, 2);
		this.Shape30.setRotationPoint(-7F, -1F, 4F);
		this.Shape30.setTextureSize(128, 64);
		this.Shape30.mirror = true;
		setRotation(this.Shape30, 0F, 0F, 0F);
		this.Shape31 = new ModelRenderer(this, 44, 19);
		this.Shape31.addBox(0F, 0F, 0F, 14, 1, 1);
		this.Shape31.setRotationPoint(5F, -0.5F, 4.5F);
		this.Shape31.setTextureSize(128, 64);
		this.Shape31.mirror = true;
		setRotation(this.Shape31, 0F, 0F, 0F);
		this.Shape32 = new ModelRenderer(this, 12, 27);
		this.Shape32.addBox(0F, 0F, 0F, 1, 1, 1);
		this.Shape32.setRotationPoint(18F, -0.5F, 3.5F);
		this.Shape32.setTextureSize(128, 64);
		this.Shape32.mirror = true;
		setRotation(this.Shape32, 0F, 0F, 0F);
		this.Shape33 = new ModelRenderer(this, 24, 29);
		this.Shape33.addBox(0F, 0F, 0F, 21, 1, 2);
		this.Shape33.setRotationPoint(-18F, -1F, 1F);
		this.Shape33.setTextureSize(128, 64);
		this.Shape33.mirror = true;
		setRotation(this.Shape33, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, ItemStack item) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Shape1.render(f5);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.Shape2.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.Shape6.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.Shape9.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		this.Shape16.render(f5);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		
		int ammo = ItemGunBase.getMag(item);
		if(ammo > 0) {
			this.Shape19.render(f5);
			this.Shape20.render(f5);
			this.Shape21.render(f5);
			this.Shape22.render(f5);
			this.Shape23.render(f5);
			this.Shape24.render(f5);
			this.Shape25.render(f5);
			this.Shape26.render(f5);
		}
		
		this.Shape27.render(f5);
		this.Shape28.render(f5);
		this.Shape29.render(f5);
		this.Shape30.render(f5);
		this.Shape31.render(f5);
		this.Shape32.render(f5);
		this.Shape33.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
