// Date: 21.02.2017 21:26:09
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEuthanasia extends ModelBase
{
  //fields
    ModelRenderer Barrel;
    ModelRenderer Tank;
    ModelRenderer ConnectorBF;
    ModelRenderer ConnectorBB;
    ModelRenderer ConnectorBeam;
    ModelRenderer ConnectorTF;
    ModelRenderer ConnectorTB;
    ModelRenderer Body;
    ModelRenderer Plate;
    ModelRenderer Beam;
    ModelRenderer Stock;
    ModelRenderer StockBack;
    ModelRenderer StockPlate;
    ModelRenderer Handle;
    ModelRenderer Trigger;
  
  public ModelEuthanasia()
  {
    this.textureWidth = 64;
    this.textureHeight = 64;
    
      this.Barrel = new ModelRenderer(this, 0, 0);
      this.Barrel.addBox(0F, 0F, 0F, 18, 3, 3);
      this.Barrel.setRotationPoint(-11F, 0.5F, -1.5F);
      this.Barrel.setTextureSize(64, 64);
      this.Barrel.mirror = true;
      setRotation(this.Barrel, 0F, 0F, 0F);
      this.Tank = new ModelRenderer(this, 0, 6);
      this.Tank.addBox(0F, 0F, 0F, 9, 5, 5);
      this.Tank.setRotationPoint(-3F, -0.5F, -2.5F);
      this.Tank.setTextureSize(64, 64);
      this.Tank.mirror = true;
      setRotation(this.Tank, 0F, 0F, 0F);
      this.ConnectorBF = new ModelRenderer(this, 52, 0);
      this.ConnectorBF.addBox(0F, 0F, 0F, 2, 8, 4);
      this.ConnectorBF.setRotationPoint(-6F, 0F, -2F);
      this.ConnectorBF.setTextureSize(64, 64);
      this.ConnectorBF.mirror = true;
      setRotation(this.ConnectorBF, 0F, 0F, 0F);
      this.ConnectorBB = new ModelRenderer(this, 28, 6);
      this.ConnectorBB.addBox(0F, 0F, 0F, 2, 8, 4);
      this.ConnectorBB.setRotationPoint(7F, 0F, -2F);
      this.ConnectorBB.setTextureSize(64, 64);
      this.ConnectorBB.mirror = true;
      setRotation(this.ConnectorBB, 0F, 0F, 0F);
      this.ConnectorBeam = new ModelRenderer(this, 0, 18);
      this.ConnectorBeam.addBox(0F, 0F, 0F, 11, 2, 4);
      this.ConnectorBeam.setRotationPoint(-4F, 6F, -2F);
      this.ConnectorBeam.setTextureSize(64, 64);
      this.ConnectorBeam.mirror = true;
      setRotation(this.ConnectorBeam, 0F, 0F, 0F);
      this.ConnectorTF = new ModelRenderer(this, 40, 12);
      this.ConnectorTF.addBox(0F, 0F, 0F, 2, 8, 4);
      this.ConnectorTF.setRotationPoint(-9F, -4F, -2F);
      this.ConnectorTF.setTextureSize(64, 64);
      this.ConnectorTF.mirror = true;
      setRotation(this.ConnectorTF, 0F, 0F, 0F);
      this.ConnectorTB = new ModelRenderer(this, 52, 12);
      this.ConnectorTB.addBox(0F, 0F, 0F, 2, 8, 4);
      this.ConnectorTB.setRotationPoint(9F, -4F, -2F);
      this.ConnectorTB.setTextureSize(64, 64);
      this.ConnectorTB.mirror = true;
      setRotation(this.ConnectorTB, 0F, 0F, 0F);
      this.Body = new ModelRenderer(this, 0, 24);
      this.Body.addBox(0F, 0F, 0F, 4, 5, 4);
      this.Body.setRotationPoint(11F, -1F, -2F);
      this.Body.setTextureSize(64, 64);
      this.Body.mirror = true;
      setRotation(this.Body, 0F, 0F, 0F);
      this.Plate = new ModelRenderer(this, 16, 24);
      this.Plate.addBox(0F, 0F, 0F, 5, 3, 4);
      this.Plate.setRotationPoint(11F, -4F, -2F);
      this.Plate.setTextureSize(64, 64);
      this.Plate.mirror = true;
      setRotation(this.Plate, 0F, 0F, 0.6457718F);
      this.Beam = new ModelRenderer(this, 0, 33);
      this.Beam.addBox(0F, 0F, 0F, 16, 1, 1);
      this.Beam.setRotationPoint(-7F, -3.5F, -0.5F);
      this.Beam.setTextureSize(64, 64);
      this.Beam.mirror = true;
      setRotation(this.Beam, 0F, 0F, 0F);
      this.Stock = new ModelRenderer(this, 0, 35);
      this.Stock.addBox(0F, 0F, 0F, 10, 2, 2);
      this.Stock.setRotationPoint(15F, 1F, -1F);
      this.Stock.setTextureSize(64, 64);
      this.Stock.mirror = true;
      setRotation(this.Stock, 0F, 0F, 0F);
      this.StockBack = new ModelRenderer(this, 0, 39);
      this.StockBack.addBox(0F, 0F, 0F, 1, 4, 2);
      this.StockBack.setRotationPoint(24F, 3F, -1F);
      this.StockBack.setTextureSize(64, 64);
      this.StockBack.mirror = true;
      setRotation(this.StockBack, 0F, 0F, 0F);
      this.StockPlate = new ModelRenderer(this, 6, 39);
      this.StockPlate.addBox(0F, -5F, 0F, 1, 5, 2);
      this.StockPlate.setRotationPoint(24F, 7F, -1F);
      this.StockPlate.setTextureSize(64, 64);
      this.StockPlate.mirror = true;
      setRotation(this.StockPlate, 0F, 0F, -0.2094395F);
      this.Handle = new ModelRenderer(this, 12, 39);
      this.Handle.addBox(0F, 0F, 0F, 2, 6, 2);
      this.Handle.setRotationPoint(13F, 4F, -1F);
      this.Handle.setTextureSize(64, 64);
      this.Handle.mirror = true;
      setRotation(this.Handle, 0F, 0F, -0.2094395F);
      this.Trigger = new ModelRenderer(this, 20, 39);
      this.Trigger.addBox(0F, 0F, 0F, 1, 4, 2);
      this.Trigger.setRotationPoint(12F, 4F, -1F);
      this.Trigger.setTextureSize(64, 64);
      this.Trigger.mirror = true;
      setRotation(this.Trigger, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.Barrel.render(f5);
    this.Tank.render(f5);
    this.ConnectorBF.render(f5);
    this.ConnectorBB.render(f5);
    this.ConnectorBeam.render(f5);
    this.ConnectorTF.render(f5);
    this.ConnectorTB.render(f5);
    this.Body.render(f5);
    this.Plate.render(f5);
    this.Beam.render(f5);
    this.Stock.render(f5);
    this.StockBack.render(f5);
    this.StockPlate.render(f5);
    this.Handle.render(f5);
    this.Trigger.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
