// Date: 08.12.2016 20:42:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import com.hbm.items.weapon.ItemGunBase;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.entity.Entity;
import net.minecraft.item.ItemStack;

public class ModelNightmare2 extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Bullet1;
	ModelRenderer Bullet2;
	ModelRenderer Bullet3;
	ModelRenderer Bullet4;
	ModelRenderer Bullet5;
	ModelRenderer Bullet6;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;

	public ModelNightmare2() {
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 3, 8, 2);
		this.Shape1.setRotationPoint(0F, 0F, 0F);
		this.Shape1.setTextureSize(64, 32);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, -0.3490659F);
		this.Shape2 = new ModelRenderer(this, 42, 0);
		this.Shape2.addBox(0F, 0F, 0F, 9, 6, 2);
		this.Shape2.setRotationPoint(-8F, -5F, 0F);
		this.Shape2.setTextureSize(64, 32);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 14);
		this.Shape3.addBox(0F, 0F, 0F, 4, 2, 1);
		this.Shape3.setRotationPoint(-0.03333334F, -3F, 0.5F);
		this.Shape3.setTextureSize(64, 32);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0.715585F);
		this.Shape4 = new ModelRenderer(this, 22, 0);
		this.Shape4.addBox(0F, 0F, 0F, 6, 4, 3);
		this.Shape4.setRotationPoint(-7F, -4F, 0F);
		this.Shape4.setTextureSize(64, 32);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 34, 8);
		this.Shape6.addBox(0F, 0F, 0F, 13, 2, 2);
		this.Shape6.setRotationPoint(-21F, -4F, 0F);
		this.Shape6.setTextureSize(64, 32);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 0, 17);
		this.Shape7.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Shape7.setRotationPoint(2F, -3F, 0.5F);
		this.Shape7.setTextureSize(64, 32);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0.715585F);
		this.Shape8 = new ModelRenderer(this, 4, 17);
		this.Shape8.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape8.setRotationPoint(2F, -4F, 0.5F);
		this.Shape8.setTextureSize(64, 32);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0.715585F);
		this.Shape9 = new ModelRenderer(this, 0, 20);
		this.Shape9.addBox(0F, 0F, 0F, 6, 1, 1);
		this.Shape9.setRotationPoint(-14F, -2F, 0.5F);
		this.Shape9.setTextureSize(64, 32);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, 0F, 0F);
		this.Shape10 = new ModelRenderer(this, 26, 8);
		this.Shape10.addBox(0F, 0F, 0F, 2, 2, 2);
		this.Shape10.setRotationPoint(-19F, -5F, 0F);
		this.Shape10.setTextureSize(64, 32);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, 0F, 0F, 0.6108652F);
		this.Shape11 = new ModelRenderer(this, 0, 10);
		this.Shape11.addBox(0F, 0F, 0F, 4, 3, 1);
		this.Shape11.setRotationPoint(-2F, 1F, 0.5F);
		this.Shape11.setTextureSize(64, 32);
		this.Shape11.mirror = true;
		setRotation(this.Shape11, 0F, 0F, 0F);
		this.Shape12 = new ModelRenderer(this, 10, 0);
		this.Shape12.addBox(0F, 0F, 0F, 1, 3, 1);
		this.Shape12.setRotationPoint(0F, 0F, 0.5F);
		this.Shape12.setTextureSize(64, 32);
		this.Shape12.mirror = true;
		setRotation(this.Shape12, 0F, 0F, 0.5235988F);
		this.Bullet1 = new ModelRenderer(this, 6, 22);
		this.Bullet1.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Bullet1.setRotationPoint(-7.5F, -4F, -1F);
		this.Bullet1.setTextureSize(64, 32);
		this.Bullet1.mirror = true;
		setRotation(this.Bullet1, 0F, 0F, 0F);
		this.Bullet2 = new ModelRenderer(this, 0, 22);
		this.Bullet2.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Bullet2.setRotationPoint(-6.5F, -4F, -1F);
		this.Bullet2.setTextureSize(64, 32);
		this.Bullet2.mirror = true;
		setRotation(this.Bullet2, 0F, 0F, 0F);
		this.Bullet3 = new ModelRenderer(this, 6, 22);
		this.Bullet3.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Bullet3.setRotationPoint(-4.5F, -4F, -1F);
		this.Bullet3.setTextureSize(64, 32);
		this.Bullet3.mirror = true;
		setRotation(this.Bullet3, 0F, 0F, 0F);
		this.Bullet4 = new ModelRenderer(this, 0, 22);
		this.Bullet4.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Bullet4.setRotationPoint(-3.5F, -4F, -1F);
		this.Bullet4.setTextureSize(64, 32);
		this.Bullet4.mirror = true;
		setRotation(this.Bullet4, 0F, 0F, 0F);
		this.Bullet5 = new ModelRenderer(this, 6, 22);
		this.Bullet5.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Bullet5.setRotationPoint(-1.5F, -4F, -1F);
		this.Bullet5.setTextureSize(64, 32);
		this.Bullet5.mirror = true;
		setRotation(this.Bullet5, 0F, 0F, 0F);
		this.Bullet6 = new ModelRenderer(this, 0, 22);
		this.Bullet6.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Bullet6.setRotationPoint(-0.5F, -4F, -1F);
		this.Bullet6.setTextureSize(64, 32);
		this.Bullet6.mirror = true;
		setRotation(this.Bullet6, 0F, 0F, 0F);
		this.Shape13 = new ModelRenderer(this, 14, 0);
		this.Shape13.addBox(0F, 0F, 0F, 1, 1, 2);
		this.Shape13.setRotationPoint(-13F, -3.5F, -2F);
		this.Shape13.setTextureSize(64, 32);
		this.Shape13.mirror = true;
		setRotation(this.Shape13, 0F, 0F, 0F);
		this.Shape14 = new ModelRenderer(this, 34, 12);
		this.Shape14.addBox(0F, 0F, 0F, 6, 1, 1);
		this.Shape14.setRotationPoint(-19F, -3.5F, -1.533333F);
		this.Shape14.setTextureSize(64, 32);
		this.Shape14.mirror = true;
		setRotation(this.Shape14, 0F, 0F, 0F);
		this.Shape15 = new ModelRenderer(this, 10, 4);
		this.Shape15.addBox(0F, 0F, 0F, 1, 5, 1);
		this.Shape15.setRotationPoint(-4F, -5F, 3F);
		this.Shape15.setTextureSize(64, 32);
		this.Shape15.mirror = true;
		setRotation(this.Shape15, 0F, 0F, 0F);
		this.Shape16 = new ModelRenderer(this, 10, 10);
		this.Shape16.addBox(-1F, -4F, 0F, 1, 4, 1);
		this.Shape16.setRotationPoint(-3F, -5F, 3F);
		this.Shape16.setTextureSize(64, 32);
		this.Shape16.mirror = true;
		setRotation(this.Shape16, 0F, 0F, -0.5235988F);
		this.Shape17 = new ModelRenderer(this, 14, 8);
		this.Shape17.addBox(0F, 0F, 0F, 5, 1, 1);
		this.Shape17.setRotationPoint(-10F, -8.5F, 3F);
		this.Shape17.setTextureSize(64, 32);
		this.Shape17.mirror = true;
		setRotation(this.Shape17, 0F, 0F, 0F);
		this.Shape18 = new ModelRenderer(this, 14, 12);
		this.Shape18.addBox(-9F, 0F, 0F, 9, 1, 1);
		this.Shape18.setRotationPoint(-10F, -8.5F, 3F);
		this.Shape18.setTextureSize(64, 32);
		this.Shape18.mirror = true;
		setRotation(this.Shape18, 0F, 0F, -0.6108652F);
		this.Shape19 = new ModelRenderer(this, 14, 10);
		this.Shape19.addBox(-5F, 0F, -1F, 5, 1, 1);
		this.Shape19.setRotationPoint(-16F, -3.5F, 4F);
		this.Shape19.setTextureSize(64, 32);
		this.Shape19.mirror = true;
		setRotation(this.Shape19, 0F, -0.4461433F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, ItemStack item) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
		
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		this.Shape16.render(f5);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		this.Shape19.render(f5);
		
		int ammo = ItemGunBase.getMag(item);
		
		if(ammo > 0)
			this.Bullet1.render(f5);
		if(ammo > 1)
			this.Bullet2.render(f5);
		if(ammo > 2)
			this.Bullet3.render(f5);
		if(ammo > 3)
			this.Bullet4.render(f5);
		if(ammo > 4)
			this.Bullet5.render(f5);
		if(ammo > 5)
			this.Bullet6.render(f5);
		
		GL11.glPushMatrix();
        GL11.glDisable(GL11.GL_TEXTURE_2D);
        GL11.glDisable(GL11.GL_LIGHTING);

        Tessellator tessellator = Tessellator.instance;
        int color = 0xFF0000;

        tessellator.startDrawing(3);
        tessellator.setColorOpaque_I(color);
        tessellator.addVertex(-19F / 16F, -3F / 16F, -1F / 16F);
        tessellator.addVertex(-150, 0, 0);
        tessellator.draw();
        
        GL11.glEnable(GL11.GL_LIGHTING);
        GL11.glEnable(GL11.GL_TEXTURE_2D);
		GL11.glPopMatrix();
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
