// Date: 13.01.2018 16:04:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLeverAction extends ModelBase {
	// fields
	ModelRenderer Barrel1;
	ModelRenderer Barrel2;
	ModelRenderer Barrel3;
	ModelRenderer Barrel4;
	ModelRenderer Grip;
	ModelRenderer Front1;
	ModelRenderer Front2;
	ModelRenderer BodyFront;
	ModelRenderer BodyTop;
	ModelRenderer BodyMain;
	ModelRenderer BodyPlate;
	ModelRenderer HandleMain;
	ModelRenderer HandleBottom;
	ModelRenderer HandleBack;
	ModelRenderer LeverFront;
	ModelRenderer LeverBottom;
	ModelRenderer LeverMid;
	ModelRenderer LeverFrontPlate;
	ModelRenderer LeverBackBottom;
	ModelRenderer Trigger;
	ModelRenderer LeverBackTop;
	ModelRenderer LeverBack;

	public ModelLeverAction() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.Barrel1 = new ModelRenderer(this, 0, 0);
		this.Barrel1.addBox(0F, 0F, 0F, 60, 3, 2);
		this.Barrel1.setRotationPoint(-60F, 1.5F, -1F);
		this.Barrel1.setTextureSize(64, 32);
		this.Barrel1.mirror = true;
		setRotation(this.Barrel1, 0F, 0F, 0F);
		this.Barrel2 = new ModelRenderer(this, 0, 5);
		this.Barrel2.addBox(0F, 0F, 0F, 60, 2, 3);
		this.Barrel2.setRotationPoint(-60F, 2F, -1.5F);
		this.Barrel2.setTextureSize(64, 32);
		this.Barrel2.mirror = true;
		setRotation(this.Barrel2, 0F, 0F, 0F);
		this.Barrel3 = new ModelRenderer(this, 0, 10);
		this.Barrel3.addBox(0F, 0F, 0F, 10, 2, 3);
		this.Barrel3.setRotationPoint(-46F, 6F, -1.5F);
		this.Barrel3.setTextureSize(64, 32);
		this.Barrel3.mirror = true;
		setRotation(this.Barrel3, 0F, 0F, 0F);
		this.Barrel4 = new ModelRenderer(this, 26, 10);
		this.Barrel4.addBox(0F, 0F, 0F, 10, 3, 2);
		this.Barrel4.setRotationPoint(-46F, 5.5F, -1F);
		this.Barrel4.setTextureSize(64, 32);
		this.Barrel4.mirror = true;
		setRotation(this.Barrel4, 0F, 0F, 0F);
		this.Grip = new ModelRenderer(this, 0, 15);
		this.Grip.addBox(0F, 0F, 0F, 36, 6, 4);
		this.Grip.setRotationPoint(-36F, 3F, -2F);
		this.Grip.setTextureSize(64, 32);
		this.Grip.mirror = true;
		setRotation(this.Grip, 0F, 0F, 0F);
		this.Front1 = new ModelRenderer(this, 50, 10);
		this.Front1.addBox(0F, 0F, 0F, 3, 2, 1);
		this.Front1.setRotationPoint(-50F, 4.5F, -0.5F);
		this.Front1.setTextureSize(64, 32);
		this.Front1.mirror = true;
		setRotation(this.Front1, 0F, 0F, 0F);
		this.Front2 = new ModelRenderer(this, 58, 10);
		this.Front2.addBox(0F, 0F, 0F, 3, 1, 2);
		this.Front2.setRotationPoint(-50F, 6.5F, -1F);
		this.Front2.setTextureSize(64, 32);
		this.Front2.mirror = true;
		setRotation(this.Front2, 0F, 0F, 0F);
		this.BodyFront = new ModelRenderer(this, 0, 25);
		this.BodyFront.addBox(0F, 0F, 0F, 3, 8, 4);
		this.BodyFront.setRotationPoint(0F, 1.5F, -2F);
		this.BodyFront.setTextureSize(64, 32);
		this.BodyFront.mirror = true;
		setRotation(this.BodyFront, 0F, 0F, 0F);
		this.BodyTop = new ModelRenderer(this, 14, 25);
		this.BodyTop.addBox(0F, 0F, 0F, 3, 1, 3);
		this.BodyTop.setRotationPoint(0F, 1F, -1.5F);
		this.BodyTop.setTextureSize(64, 32);
		this.BodyTop.mirror = true;
		setRotation(this.BodyTop, 0F, 0F, 0F);
		this.BodyMain = new ModelRenderer(this, 0, 37);
		this.BodyMain.addBox(0F, 0F, 0F, 12, 7, 4);
		this.BodyMain.setRotationPoint(3F, 2.5F, -2F);
		this.BodyMain.setTextureSize(64, 32);
		this.BodyMain.mirror = true;
		setRotation(this.BodyMain, 0F, 0F, 0F);
		this.BodyPlate = new ModelRenderer(this, 26, 25);
		this.BodyPlate.addBox(0F, 0F, 0F, 10, 2, 3);
		this.BodyPlate.setRotationPoint(3F, 1F, -1.5F);
		this.BodyPlate.setTextureSize(64, 32);
		this.BodyPlate.mirror = true;
		setRotation(this.BodyPlate, 0F, 0F, 0.1570796F);
		this.HandleMain = new ModelRenderer(this, 0, 48);
		this.HandleMain.addBox(0F, 0F, 0F, 18, 5, 4);
		this.HandleMain.setRotationPoint(15F, 4F, -2F);
		this.HandleMain.setTextureSize(128, 64);
		this.HandleMain.mirror = true;
		setRotation(this.HandleMain, 0F, 0F, 0.4363323F);
		this.HandleBottom = new ModelRenderer(this, 0, 57);
		this.HandleBottom.addBox(4F, 4.5F, 0F, 13, 1, 4);
		this.HandleBottom.setRotationPoint(15F, 4F, -2F);
		this.HandleBottom.setTextureSize(128, 64);
		this.HandleBottom.mirror = true;
		setRotation(this.HandleBottom, 0F, 0F, 0.4363323F);
		this.HandleBack = new ModelRenderer(this, 34, 57);
		this.HandleBack.addBox(17.5F, 0.5F, 0F, 1, 4, 3);
		this.HandleBack.setRotationPoint(15F, 4F, -1.5F);
		this.HandleBack.setTextureSize(128, 64);
		this.HandleBack.mirror = true;
		setRotation(this.HandleBack, 0F, 0F, 0.4363323F);
		this.LeverFront = new ModelRenderer(this, 62, 30);
		this.LeverFront.addBox(-1F, 0F, 0F, 2, 4, 2);
		this.LeverFront.setRotationPoint(7F, 9F, -1F);
		this.LeverFront.setTextureSize(128, 64);
		this.LeverFront.mirror = true;
		setRotation(this.LeverFront, 0F, 0F, 0F);
		this.LeverBottom = new ModelRenderer(this, 70, 30);
		this.LeverBottom.addBox(0F, 4F, 0F, 6, 1, 2);
		this.LeverBottom.setRotationPoint(7F, 9F, -1F);
		this.LeverBottom.setTextureSize(128, 64);
		this.LeverBottom.mirror = true;
		setRotation(this.LeverBottom, 0F, 0F, 0F);
		this.LeverMid = new ModelRenderer(this, 62, 36);
		this.LeverMid.addBox(6F, 0F, 0F, 1, 5, 2);
		this.LeverMid.setRotationPoint(7F, 9F, -1F);
		this.LeverMid.setTextureSize(128, 64);
		this.LeverMid.mirror = true;
		setRotation(this.LeverMid, 0F, 0F, 0F);
		this.LeverFrontPlate = new ModelRenderer(this, 68, 39);
		this.LeverFrontPlate.addBox(7F, -1.5F, 0F, 9, 1, 2);
		this.LeverFrontPlate.setRotationPoint(7F, 9F, -1F);
		this.LeverFrontPlate.setTextureSize(128, 64);
		this.LeverFrontPlate.mirror = true;
		setRotation(this.LeverFrontPlate, 0F, 0F, 0.7853982F);
		this.LeverBackBottom = new ModelRenderer(this, 70, 33);
		this.LeverBackBottom.addBox(12F, 10F, 0F, 6, 1, 2);
		this.LeverBackBottom.setRotationPoint(7F, 9F, -1F);
		this.LeverBackBottom.setTextureSize(128, 64);
		this.LeverBackBottom.mirror = true;
		setRotation(this.LeverBackBottom, 0F, 0F, 0F);
		this.Trigger = new ModelRenderer(this, 88, 30);
		this.Trigger.addBox(-1F, 0F, 0F, 1, 3, 1);
		this.Trigger.setRotationPoint(12.5F, 9F, -0.5F);
		this.Trigger.setTextureSize(128, 64);
		this.Trigger.mirror = true;
		setRotation(this.Trigger, 0F, 0F, 0.3490659F);
		this.LeverBackTop = new ModelRenderer(this, 68, 36);
		this.LeverBackTop.addBox(8F, -2F, 0F, 11, 1, 2);
		this.LeverBackTop.setRotationPoint(7F, 9F, -1F);
		this.LeverBackTop.setTextureSize(128, 64);
		this.LeverBackTop.mirror = true;
		setRotation(this.LeverBackTop, 0F, 0F, 0.4363323F);
		this.LeverBack = new ModelRenderer(this, 62, 43);
		this.LeverBack.addBox(17F, 6F, 0F, 1, 4, 2);
		this.LeverBack.setRotationPoint(7F, 9F, -1F);
		this.LeverBack.setTextureSize(128, 64);
		this.LeverBack.mirror = true;
		setRotation(this.LeverBack, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Barrel1.render(f5);
		this.Barrel2.render(f5);
		this.Barrel3.render(f5);
		this.Barrel4.render(f5);
		this.Grip.render(f5);
		this.Front1.render(f5);
		this.Front2.render(f5);
		this.BodyFront.render(f5);
		this.BodyTop.render(f5);
		this.BodyMain.render(f5);
		this.BodyPlate.render(f5);
		this.HandleMain.render(f5);
		this.HandleBottom.render(f5);
		this.HandleBack.render(f5);
		this.LeverFront.render(f5);
		this.LeverBottom.render(f5);
		this.LeverMid.render(f5);
		this.LeverFrontPlate.render(f5);
		this.LeverBackBottom.render(f5);
		this.Trigger.render(f5);
		this.LeverBackTop.render(f5);
		this.LeverBack.render(f5);
	}

	public void renderAnim(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, float anim) {
		this.LeverFront.rotateAngleZ += anim;
		this.LeverBottom.rotateAngleZ += anim;
		this.LeverMid.rotateAngleZ += anim;
		this.LeverFrontPlate.rotateAngleZ += anim;
		this.LeverBackBottom.rotateAngleZ += anim;
		this.LeverBackTop.rotateAngleZ += anim;
		this.LeverBack.rotateAngleZ += anim;
		
		render(entity, f, f1, f2, f3, f4, f5);
		
		setRotation(this.LeverFront, 0F, 0F, 0F);
		setRotation(this.LeverBottom, 0F, 0F, 0F);
		setRotation(this.LeverMid, 0F, 0F, 0F);
		setRotation(this.LeverFrontPlate, 0F, 0F, 0.7853982F);
		setRotation(this.LeverBackBottom, 0F, 0F, 0F);
		setRotation(this.LeverBackTop, 0F, 0F, 0.4363323F);
		setRotation(this.LeverBack, 0F, 0F, 0F);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
