// Date: 14.01.2018 22:26:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.entity.Entity;

public class ModelBoltAction extends ModelBase {
	// fields
	ModelRenderer Barrel1;
	ModelRenderer Barrel2;
	ModelRenderer Grip;
	ModelRenderer BodyFront;
	ModelRenderer BodyMain;
	ModelRenderer LeverFront;
	ModelRenderer LeverBottom;
	ModelRenderer LeverMid;
	ModelRenderer Trigger;
	ModelRenderer GripFront;
	ModelRenderer GropFrontBottom;
	ModelRenderer GripBottom;
	ModelRenderer Bolt;
	ModelRenderer ChamberFront;
	ModelRenderer ChamberBack;
	ModelRenderer BodyBack;
	ModelRenderer LeverTip;
	ModelRenderer Lever;
	ModelRenderer HandleFront;
	ModelRenderer Pointer;
	ModelRenderer HandleBottom;
	ModelRenderer HandleGrip;

	public ModelBoltAction() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.Barrel1 = new ModelRenderer(this, 0, 0);
		this.Barrel1.addBox(0F, 0F, 0F, 60, 3, 2);
		this.Barrel1.setRotationPoint(-60F, 1.5F, -1F);
		this.Barrel1.setTextureSize(64, 32);
		this.Barrel1.mirror = true;
		setRotation(this.Barrel1, 0F, 0F, 0F);
		this.Barrel2 = new ModelRenderer(this, 0, 5);
		this.Barrel2.addBox(0F, 0F, 0F, 60, 2, 3);
		this.Barrel2.setRotationPoint(-60F, 2F, -1.5F);
		this.Barrel2.setTextureSize(64, 32);
		this.Barrel2.mirror = true;
		setRotation(this.Barrel2, 0F, 0F, 0F);
		this.Grip = new ModelRenderer(this, 0, 10);
		this.Grip.addBox(0F, 0F, 0F, 28, 5, 4);
		this.Grip.setRotationPoint(-28F, 3F, -2F);
		this.Grip.setTextureSize(64, 32);
		this.Grip.mirror = true;
		setRotation(this.Grip, 0F, 0F, 0F);
		this.BodyFront = new ModelRenderer(this, 0, 19);
		this.BodyFront.addBox(0F, 0F, 0F, 3, 7, 4);
		this.BodyFront.setRotationPoint(0F, 2.5F, -2F);
		this.BodyFront.setTextureSize(64, 32);
		this.BodyFront.mirror = true;
		setRotation(this.BodyFront, 0F, 0F, 0F);
		this.BodyMain = new ModelRenderer(this, 14, 19);
		this.BodyMain.addBox(0F, 0F, 0F, 8, 7, 4);
		this.BodyMain.setRotationPoint(3F, 2.5F, -2F);
		this.BodyMain.setTextureSize(64, 32);
		this.BodyMain.mirror = true;
		setRotation(this.BodyMain, 0F, 0F, 0F);
		this.LeverFront = new ModelRenderer(this, 62, 30);
		this.LeverFront.addBox(-1F, 0F, 0F, 2, 4, 2);
		this.LeverFront.setRotationPoint(7F, 9F, -1F);
		this.LeverFront.setTextureSize(64, 32);
		this.LeverFront.mirror = true;
		setRotation(this.LeverFront, 0F, 0F, 0F);
		this.LeverBottom = new ModelRenderer(this, 70, 30);
		this.LeverBottom.addBox(0F, 4F, 0F, 6, 1, 2);
		this.LeverBottom.setRotationPoint(7F, 9F, -1F);
		this.LeverBottom.setTextureSize(64, 32);
		this.LeverBottom.mirror = true;
		setRotation(this.LeverBottom, 0F, 0F, 0F);
		this.LeverMid = new ModelRenderer(this, 62, 36);
		this.LeverMid.addBox(6F, 0F, 0F, 1, 5, 2);
		this.LeverMid.setRotationPoint(7F, 9F, -1F);
		this.LeverMid.setTextureSize(64, 32);
		this.LeverMid.mirror = true;
		setRotation(this.LeverMid, 0F, 0F, 0F);
		this.Trigger = new ModelRenderer(this, 88, 30);
		this.Trigger.addBox(-1F, 0F, 0F, 1, 3, 1);
		this.Trigger.setRotationPoint(12.5F, 9F, -0.5F);
		this.Trigger.setTextureSize(64, 32);
		this.Trigger.mirror = true;
		setRotation(this.Trigger, 0F, 0F, 0.3490659F);
		this.GripFront = new ModelRenderer(this, 0, 30);
		this.GripFront.addBox(0F, 0F, 0F, 18, 3, 4);
		this.GripFront.setRotationPoint(-46F, 3F, -2F);
		this.GripFront.setTextureSize(128, 64);
		this.GripFront.mirror = true;
		setRotation(this.GripFront, 0F, 0F, 0F);
		this.GropFrontBottom = new ModelRenderer(this, 0, 37);
		this.GropFrontBottom.addBox(0F, 0F, 0F, 18, 1, 2);
		this.GropFrontBottom.setRotationPoint(-46F, 6F, -1F);
		this.GropFrontBottom.setTextureSize(128, 64);
		this.GropFrontBottom.mirror = true;
		setRotation(this.GropFrontBottom, 0F, 0F, 0F);
		this.GripBottom = new ModelRenderer(this, 0, 40);
		this.GripBottom.addBox(0F, 0F, 0F, 28, 1, 2);
		this.GripBottom.setRotationPoint(-28F, 8F, -1F);
		this.GripBottom.setTextureSize(128, 64);
		this.GripBottom.mirror = true;
		setRotation(this.GripBottom, 0F, 0F, 0F);
		this.Bolt = new ModelRenderer(this, 0, 43);
		this.Bolt.addBox(0F, 0F, 0F, 10, 2, 2);
		this.Bolt.setRotationPoint(3F, 2F, -1F);
		this.Bolt.setTextureSize(128, 64);
		this.Bolt.mirror = true;
		setRotation(this.Bolt, 0F, 0F, 0F);
		this.ChamberFront = new ModelRenderer(this, 0, 47);
		this.ChamberFront.addBox(0F, 0F, 0F, 3, 1, 3);
		this.ChamberFront.setRotationPoint(0F, 1.5F, -1.5F);
		this.ChamberFront.setTextureSize(128, 64);
		this.ChamberFront.mirror = true;
		setRotation(this.ChamberFront, 0F, 0F, 0F);
		this.ChamberBack = new ModelRenderer(this, 12, 47);
		this.ChamberBack.addBox(0F, 0F, 0F, 3, 1, 3);
		this.ChamberBack.setRotationPoint(8F, 1.5F, -1.5F);
		this.ChamberBack.setTextureSize(128, 64);
		this.ChamberBack.mirror = true;
		setRotation(this.ChamberBack, 0F, 0F, 0F);
		this.BodyBack = new ModelRenderer(this, 0, 51);
		this.BodyBack.addBox(0F, 0F, 0F, 4, 6, 4);
		this.BodyBack.setRotationPoint(11F, 3.5F, -2F);
		this.BodyBack.setTextureSize(128, 64);
		this.BodyBack.mirror = true;
		setRotation(this.BodyBack, 0F, 0F, 0F);
		this.LeverTip = new ModelRenderer(this, 24, 43);
		this.LeverTip.addBox(0F, -1F, 3F, 2, 2, 2);
		this.LeverTip.setRotationPoint(11F, 3F, 0F);
		this.LeverTip.setTextureSize(128, 64);
		this.LeverTip.mirror = true;
		setRotation(this.LeverTip, -0.4363323F, 0F, 0F);
		this.Lever = new ModelRenderer(this, 32, 43);
		this.Lever.addBox(0F, -0.5F, 0F, 1, 1, 4);
		this.Lever.setRotationPoint(11.5F, 3F, 0F);
		this.Lever.setTextureSize(128, 64);
		this.Lever.mirror = true;
		setRotation(this.Lever, -0.4363323F, 0F, 0F);
		this.HandleFront = new ModelRenderer(this, 16, 51);
		this.HandleFront.addBox(0F, 0F, 0F, 9, 5, 4);
		this.HandleFront.setRotationPoint(15F, 4.5F, -2F);
		this.HandleFront.setTextureSize(128, 64);
		this.HandleFront.mirror = true;
		setRotation(this.HandleFront, 0F, 0F, 0.4363323F);
		this.Pointer = new ModelRenderer(this, 42, 43);
		this.Pointer.addBox(0F, 0F, 0F, 3, 1, 1);
		this.Pointer.setRotationPoint(-49F, 5.5F, -0.5F);
		this.Pointer.setTextureSize(128, 64);
		this.Pointer.mirror = true;
		setRotation(this.Pointer, 0F, 0F, 0F);
		this.HandleBottom = new ModelRenderer(this, 64, 10);
		this.HandleBottom.addBox(0F, -8F, 0F, 23, 8, 4);
		this.HandleBottom.setRotationPoint(19F, 16F, -2F);
		this.HandleBottom.setTextureSize(128, 64);
		this.HandleBottom.mirror = true;
		setRotation(this.HandleBottom, 0F, 0F, 0F);
		this.HandleGrip = new ModelRenderer(this, 38, 19);
		this.HandleGrip.addBox(0F, 0F, 0F, 2, 5, 4);
		this.HandleGrip.setRotationPoint(17F, 9.5F, -2F);
		this.HandleGrip.setTextureSize(128, 64);
		this.HandleGrip.mirror = true;
		setRotation(this.HandleGrip, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Barrel1.render(f5);
		this.Barrel2.render(f5);
		this.Grip.render(f5);
		this.BodyFront.render(f5);
		this.BodyMain.render(f5);
		this.LeverFront.render(f5);
		this.LeverBottom.render(f5);
		this.LeverMid.render(f5);
		this.Trigger.render(f5);
		this.GripFront.render(f5);
		this.GropFrontBottom.render(f5);
		this.GripBottom.render(f5);
		this.Bolt.render(f5);
		this.ChamberFront.render(f5);
		this.ChamberBack.render(f5);
		this.BodyBack.render(f5);
		this.LeverTip.render(f5);
		this.Lever.render(f5);
		this.HandleFront.render(f5);
		this.Pointer.render(f5);
		this.HandleBottom.render(f5);
		this.HandleGrip.render(f5);
		
		GL11.glPushMatrix();
        GL11.glDisable(GL11.GL_TEXTURE_2D);
        GL11.glDisable(GL11.GL_LIGHTING);

        Tessellator tessellator = Tessellator.instance;
        int color = 0x00FF00;

        tessellator.startDrawing(3);
        tessellator.setColorOpaque_I(color);
        tessellator.addVertex(-32F / 16F, 0 + 4F / 16F, 0);
        tessellator.addVertex(-150, 0, 0);
        tessellator.draw();
        
        GL11.glEnable(GL11.GL_LIGHTING);
        GL11.glEnable(GL11.GL_TEXTURE_2D);
		GL11.glPopMatrix();
	}

	public void renderAnim(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, float rot, float tran) {

		this.LeverTip.rotateAngleX += rot;
		this.Lever.rotateAngleX += rot;
		this.Bolt.offsetX += tran;
		this.LeverTip.offsetX += tran;
		this.Lever.offsetX += tran;
		
		render(entity, f, f1, f2, f3, f4, f5);

		setRotation(this.LeverTip, -0.4363323F, 0F, 0F);
		setRotation(this.Lever, -0.4363323F, 0F, 0F);
		this.Bolt.offsetX -= tran;
		this.LeverTip.offsetX -= tran;
		this.Lever.offsetX -= tran;
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
