// Date: 14.02.2017 20:27:10
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSpark extends ModelBase
{
  //fields
    ModelRenderer BarrelMain;
    ModelRenderer BarrelSide;
    ModelRenderer PlateFront;
    ModelRenderer Sight;
    ModelRenderer Grip;
    ModelRenderer Cell1;
    ModelRenderer Cell2;
    ModelRenderer Cell3;
    ModelRenderer Cell4;
    ModelRenderer Cell5;
    ModelRenderer Cell8;
    ModelRenderer Cell7;
    ModelRenderer Cell6;
    ModelRenderer PlateBack;
    ModelRenderer Body;
    ModelRenderer Handle1;
    ModelRenderer Handle2;
  
  public ModelSpark()
  {
    this.textureWidth = 64;
    this.textureHeight = 64;
    
      this.BarrelMain = new ModelRenderer(this, 0, 0);
      this.BarrelMain.addBox(0F, 0F, 0F, 18, 6, 6);
      this.BarrelMain.setRotationPoint(-18F, 0F, -3F);
      this.BarrelMain.setTextureSize(64, 64);
      this.BarrelMain.mirror = true;
      setRotation(this.BarrelMain, 0F, 0F, 0F);
      this.BarrelSide = new ModelRenderer(this, 0, 12);
      this.BarrelSide.addBox(0F, -3F, -3F, 14, 6, 6);
      this.BarrelSide.setRotationPoint(-14F, 3F, 0F);
      this.BarrelSide.setTextureSize(64, 64);
      this.BarrelSide.mirror = true;
      setRotation(this.BarrelSide, 0.7853982F, 0F, 0F);
      this.PlateFront = new ModelRenderer(this, 40, 12);
      this.PlateFront.addBox(0F, 0F, 0F, 2, 8, 8);
      this.PlateFront.setRotationPoint(0F, -1F, -4F);
      this.PlateFront.setTextureSize(64, 64);
      this.PlateFront.mirror = true;
      setRotation(this.PlateFront, 0F, 0F, 0F);
      this.Sight = new ModelRenderer(this, 48, 0);
      this.Sight.addBox(0F, 0F, 0F, 1, 4, 2);
      this.Sight.setRotationPoint(-16F, -4F, -1F);
      this.Sight.setTextureSize(64, 64);
      this.Sight.mirror = true;
      setRotation(this.Sight, 0F, 0F, 0F);
      this.Grip = new ModelRenderer(this, 0, 24);
      this.Grip.addBox(0F, 0F, 0F, 12, 2, 2);
      this.Grip.setRotationPoint(-10F, 5F, -6F);
      this.Grip.setTextureSize(64, 64);
      this.Grip.mirror = true;
      setRotation(this.Grip, 0F, 0F, 0F);
      this.Cell1 = new ModelRenderer(this, 0, 28);
      this.Cell1.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell1.setRotationPoint(2F, 3F, 0F);
      this.Cell1.setTextureSize(64, 64);
      this.Cell1.mirror = true;
      setRotation(this.Cell1, 0F, 0F, 0F);
      this.Cell2 = new ModelRenderer(this, 0, 32);
      this.Cell2.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell2.setRotationPoint(2F, 3F, 0F);
      this.Cell2.setTextureSize(64, 64);
      this.Cell2.mirror = true;
      setRotation(this.Cell2, 0.7853982F, 0F, 0F);
      this.Cell3 = new ModelRenderer(this, 0, 36);
      this.Cell3.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell3.setRotationPoint(2F, 3F, 0F);
      this.Cell3.setTextureSize(64, 64);
      this.Cell3.mirror = true;
      setRotation(this.Cell3, 1.570796F, 0F, 0F);
      this.Cell4 = new ModelRenderer(this, 0, 40);
      this.Cell4.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell4.setRotationPoint(2F, 3F, 0F);
      this.Cell4.setTextureSize(64, 64);
      this.Cell4.mirror = true;
      setRotation(this.Cell4, 2.356194F, 0F, 0F);
      this.Cell5 = new ModelRenderer(this, 0, 44);
      this.Cell5.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell5.setRotationPoint(2F, 3F, 0F);
      this.Cell5.setTextureSize(64, 64);
      this.Cell5.mirror = true;
      setRotation(this.Cell5, 3.141593F, 0F, 0F);
      this.Cell8 = new ModelRenderer(this, 0, 48);
      this.Cell8.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell8.setRotationPoint(2F, 3F, 0F);
      this.Cell8.setTextureSize(64, 64);
      this.Cell8.mirror = true;
      setRotation(this.Cell8, -0.7853982F, 0F, 0F);
      this.Cell7 = new ModelRenderer(this, 0, 52);
      this.Cell7.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell7.setRotationPoint(2F, 3F, 0F);
      this.Cell7.setTextureSize(64, 64);
      this.Cell7.mirror = true;
      setRotation(this.Cell7, -1.570796F, 0F, 0F);
      this.Cell6 = new ModelRenderer(this, 0, 56);
      this.Cell6.addBox(0F, -3.5F, -1F, 3, 2, 2);
      this.Cell6.setRotationPoint(2F, 3F, 0F);
      this.Cell6.setTextureSize(64, 64);
      this.Cell6.mirror = true;
      setRotation(this.Cell6, -2.356194F, 0F, 0F);
      this.PlateBack = new ModelRenderer(this, 10, 28);
      this.PlateBack.addBox(0F, 0F, 0F, 2, 8, 8);
      this.PlateBack.setRotationPoint(5F, -1F, -4F);
      this.PlateBack.setTextureSize(64, 64);
      this.PlateBack.mirror = true;
      setRotation(this.PlateBack, 0F, 0F, 0F);
      this.Body = new ModelRenderer(this, 10, 44);
      this.Body.addBox(0F, 0F, 0F, 8, 6, 4);
      this.Body.setRotationPoint(7F, 1F, -2F);
      this.Body.setTextureSize(64, 64);
      this.Body.mirror = true;
      setRotation(this.Body, 0F, 0F, 0F);
      this.Handle1 = new ModelRenderer(this, 10, 54);
      this.Handle1.addBox(0F, 0F, 0F, 2, 2, 2);
      this.Handle1.setRotationPoint(15F, 4F, -1F);
      this.Handle1.setTextureSize(64, 64);
      this.Handle1.mirror = true;
      setRotation(this.Handle1, 0F, 0F, 0F);
      this.Handle2 = new ModelRenderer(this, 18, 54);
      this.Handle2.addBox(0F, 0F, 0F, 1, 4, 1);
      this.Handle2.setRotationPoint(17F, 2F, -0.5F);
      this.Handle2.setTextureSize(64, 64);
      this.Handle2.mirror = true;
      setRotation(this.Handle2, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.BarrelMain.render(f5);
    this.BarrelSide.render(f5);
    this.PlateFront.render(f5);
	GL11.glDisable(GL11.GL_CULL_FACE);
    this.Sight.render(f5);
	GL11.glEnable(GL11.GL_CULL_FACE);
    this.Grip.render(f5);
    this.Cell1.render(f5);
    this.Cell2.render(f5);
    this.Cell3.render(f5);
    this.Cell4.render(f5);
    this.Cell5.render(f5);
    this.Cell8.render(f5);
    this.Cell7.render(f5);
    this.Cell6.render(f5);
    this.PlateBack.render(f5);
    this.Body.render(f5);
    this.Handle1.render(f5);
    this.Handle2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
