// Date: 20.07.2015 22:08:24
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRocketOld extends ModelBase {
	// fields
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;

	public ModelRocketOld() {
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.Shape7 = new ModelRenderer(this, 10, 0);
		this.Shape7.addBox(0F, 0F, 0F, 1, 2, 2);
		this.Shape7.setRotationPoint(-3F, -2F, -0.5F);
		this.Shape7.setTextureSize(64, 32);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0F);
		this.Shape8 = new ModelRenderer(this, 0, 4);
		this.Shape8.addBox(0F, 0F, 0F, 10, 1, 1);
		this.Shape8.setRotationPoint(-8F, -1.5F, 0F);
		this.Shape8.setTextureSize(64, 32);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
		this.Shape9 = new ModelRenderer(this, 0, 0);
		this.Shape9.addBox(0F, 0F, 0F, 3, 2, 2);
		this.Shape9.setRotationPoint(-6.5F, -2F, -0.5F);
		this.Shape9.setTextureSize(64, 32);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
