// Date: 16.05.2015 19:38:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTestRender extends ModelBase
{
  //fields
    ModelRenderer MainBlock;
  
  public ModelTestRender()
  {
    this.textureWidth = 64;
    this.textureHeight = 32;
    
      this.MainBlock = new ModelRenderer(this, 0, 0);
      this.MainBlock.addBox(0F, 0F, 0F, 12, 16, 12);
      this.MainBlock.setRotationPoint(-6F, 8F, -6F);
      this.MainBlock.setTextureSize(64, 32);
      this.MainBlock.mirror = true;
      setRotation(this.MainBlock, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.MainBlock.render(f5);
  }
  
  public void renderModel(float f) {
	    this.MainBlock.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
