// Date: 03.11.2016 19:00:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMP40 extends ModelBase {
	// fields
	ModelRenderer Body;
	ModelRenderer Barrel;
	ModelRenderer Scope;
	ModelRenderer ClipPivot;
	ModelRenderer ClipPivotBack;
	ModelRenderer Clip;
	ModelRenderer BarrelBottom;
	ModelRenderer BodyStock;
	ModelRenderer BodyStockBottom;
	ModelRenderer BodyBack;
	ModelRenderer Handle;
	ModelRenderer TriggerFrame;
	ModelRenderer Trigger;
	ModelRenderer Bar;
	ModelRenderer BarFront;

	public ModelMP40() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.Body = new ModelRenderer(this, 0, 0);
		this.Body.addBox(0F, 0F, 0F, 40, 4, 4);
		this.Body.setRotationPoint(-10F, 0F, -2F);
		this.Body.setTextureSize(128, 64);
		this.Body.mirror = true;
		setRotation(this.Body, 0F, 0F, 0F);
		this.Barrel = new ModelRenderer(this, 88, 0);
		this.Barrel.addBox(0F, 0F, 0F, 17, 2, 2);
		this.Barrel.setRotationPoint(-27F, 1F, -1F);
		this.Barrel.setTextureSize(128, 64);
		this.Barrel.mirror = true;
		setRotation(this.Barrel, 0F, 0F, 0F);
		this.Scope = new ModelRenderer(this, 88, 4);
		this.Scope.addBox(0F, 0F, 0F, 2, 3, 2);
		this.Scope.setRotationPoint(-25F, -2F, -1F);
		this.Scope.setTextureSize(128, 64);
		this.Scope.mirror = true;
		setRotation(this.Scope, 0F, 0F, 0F);
		this.ClipPivot = new ModelRenderer(this, 0, 17);
		this.ClipPivot.addBox(0F, 0F, 0F, 4, 5, 3);
		this.ClipPivot.setRotationPoint(-3F, 4F, -1.5F);
		this.ClipPivot.setTextureSize(128, 64);
		this.ClipPivot.mirror = true;
		setRotation(this.ClipPivot, 0F, 0F, 0F);
		this.ClipPivotBack = new ModelRenderer(this, 14, 17);
		this.ClipPivotBack.addBox(0F, 0F, 0F, 3, 3, 3);
		this.ClipPivotBack.setRotationPoint(1F, 4F, -1.5F);
		this.ClipPivotBack.setTextureSize(128, 64);
		this.ClipPivotBack.mirror = true;
		setRotation(this.ClipPivotBack, 0F, 0F, 0F);
		this.Clip = new ModelRenderer(this, 0, 25);
		this.Clip.addBox(0F, 0F, 0F, 3, 18, 2);
		this.Clip.setRotationPoint(-2.5F, 9F, -1F);
		this.Clip.setTextureSize(128, 64);
		this.Clip.mirror = true;
		setRotation(this.Clip, 0F, 0F, 0F);
		this.BarrelBottom = new ModelRenderer(this, 96, 4);
		this.BarrelBottom.addBox(0F, 0F, 0F, 14, 1, 1);
		this.BarrelBottom.setRotationPoint(-24F, 2.5F, -0.5F);
		this.BarrelBottom.setTextureSize(128, 64);
		this.BarrelBottom.mirror = true;
		setRotation(this.BarrelBottom, 0F, 0F, 0F);
		this.BodyStock = new ModelRenderer(this, 0, 8);
		this.BodyStock.addBox(0F, 0F, 0F, 26, 4, 5);
		this.BodyStock.setRotationPoint(4F, 3F, -2.5F);
		this.BodyStock.setTextureSize(128, 64);
		this.BodyStock.mirror = true;
		setRotation(this.BodyStock, 0F, 0F, 0F);
		this.BodyStockBottom = new ModelRenderer(this, 62, 11);
		this.BodyStockBottom.addBox(0F, 0F, 0F, 26, 3, 3);
		this.BodyStockBottom.setRotationPoint(4F, 7F, -1.5F);
		this.BodyStockBottom.setTextureSize(128, 64);
		this.BodyStockBottom.mirror = true;
		setRotation(this.BodyStockBottom, 0F, 0F, 0F);
		this.BodyBack = new ModelRenderer(this, 10, 25);
		this.BodyBack.addBox(0F, 0F, 0F, 7, 7, 3);
		this.BodyBack.setRotationPoint(30F, 0F, -1.5F);
		this.BodyBack.setTextureSize(128, 64);
		this.BodyBack.mirror = true;
		setRotation(this.BodyBack, 0F, 0F, 0.7853982F);
		this.Handle = new ModelRenderer(this, 30, 17);
		this.Handle.addBox(0F, 0F, 0F, 4, 10, 3);
		this.Handle.setRotationPoint(27F, 10F, -1.5F);
		this.Handle.setTextureSize(128, 64);
		this.Handle.mirror = true;
		setRotation(this.Handle, 0F, 0F, -0.4363323F);
		this.TriggerFrame = new ModelRenderer(this, 44, 17);
		this.TriggerFrame.addBox(0F, 0F, 0F, 6, 4, 2);
		this.TriggerFrame.setRotationPoint(23F, 10F, -1F);
		this.TriggerFrame.setTextureSize(128, 64);
		this.TriggerFrame.mirror = true;
		setRotation(this.TriggerFrame, 0F, 0F, 0F);
		this.Trigger = new ModelRenderer(this, 26, 17);
		this.Trigger.addBox(-1F, 0F, 0F, 1, 3, 1);
		this.Trigger.setRotationPoint(27F, 10F, -0.5F);
		this.Trigger.setTextureSize(128, 64);
		this.Trigger.mirror = true;
		setRotation(this.Trigger, 0F, 0F, 0.4363323F);
		this.Bar = new ModelRenderer(this, 60, 17);
		this.Bar.addBox(0F, 0F, 0F, 23, 1, 1);
		this.Bar.setRotationPoint(7F, 7.5F, -3F);
		this.Bar.setTextureSize(128, 64);
		this.Bar.mirror = true;
		setRotation(this.Bar, 0F, 0F, 0F);
		this.BarFront = new ModelRenderer(this, 0, 45);
		this.BarFront.addBox(-2.5F, -0.5F, 0F, 5, 1, 1);
		this.BarFront.setRotationPoint(7F, 8F, -3F);
		this.BarFront.setTextureSize(128, 64);
		this.BarFront.mirror = true;
		setRotation(this.BarFront, 0F, 0F, 0.7853982F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Body.render(f5);
		this.Barrel.render(f5);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.Scope.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
		this.ClipPivot.render(f5);
		this.ClipPivotBack.render(f5);
		this.Clip.render(f5);
		this.BarrelBottom.render(f5);
		this.BodyStock.render(f5);
		this.BodyStockBottom.render(f5);
		this.BodyBack.render(f5);
		this.Handle.render(f5);
		GL11.glDisable(GL11.GL_CULL_FACE);
		this.TriggerFrame.render(f5);
		GL11.glEnable(GL11.GL_CULL_FACE);
		this.Trigger.render(f5);
		this.Bar.render(f5);
		this.BarFront.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
