// Date: 24.10.2018 10:31:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCalDualStock extends ModelBase {
	// fields
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;

	public ModelCalDualStock() {
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.Shape8 = new ModelRenderer(this, 0, 0);
		this.Shape8.addBox(0F, 0F, 0F, 15, 6, 3);
		this.Shape8.setRotationPoint(0F, 1F, -1.5F);
		this.Shape8.setTextureSize(64, 32);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
		this.Shape9 = new ModelRenderer(this, 0, 9);
		this.Shape9.addBox(0F, 0F, 0F, 6, 1, 2);
		this.Shape9.setRotationPoint(7F, 7F, -1F);
		this.Shape9.setTextureSize(64, 32);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, 0F, 0F);
		this.Shape10 = new ModelRenderer(this, 0, 12);
		this.Shape10.addBox(0F, 0F, 0F, 2, 5, 2);
		this.Shape10.setRotationPoint(10F, 8F, -1F);
		this.Shape10.setTextureSize(64, 32);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, 0F, 0F, -0.2617994F);
		this.Shape11 = new ModelRenderer(this, 0, 26);
		this.Shape11.addBox(0F, 0F, 0F, 3, 4, 2);
		this.Shape11.setRotationPoint(19F, 3F, -1F);
		this.Shape11.setTextureSize(64, 32);
		this.Shape11.mirror = true;
		setRotation(this.Shape11, 0F, 0F, 0F);
		this.Shape12 = new ModelRenderer(this, 0, 22);
		this.Shape12.addBox(-4F, 0F, 0F, 4, 2, 2);
		this.Shape12.setRotationPoint(19F, 3F, -1F);
		this.Shape12.setTextureSize(64, 32);
		this.Shape12.mirror = true;
		setRotation(this.Shape12, 0F, 0F, -0.1115358F);
		this.Shape13 = new ModelRenderer(this, 10, 28);
		this.Shape13.addBox(-5F, -2F, 0F, 5, 2, 2);
		this.Shape13.setRotationPoint(19F, 7F, -1F);
		this.Shape13.setTextureSize(64, 32);
		this.Shape13.mirror = true;
		setRotation(this.Shape13, 0F, 0F, 0.2617994F);
		this.Shape14 = new ModelRenderer(this, 12, 23);
		this.Shape14.addBox(0F, 0F, 0F, 1, 3, 2);
		this.Shape14.setRotationPoint(22F, 3F, -1F);
		this.Shape14.setTextureSize(64, 32);
		this.Shape14.mirror = true;
		setRotation(this.Shape14, 0F, 0F, 0.3490659F);
		this.Shape15 = new ModelRenderer(this, 42, 0);
		this.Shape15.addBox(0F, 0F, 0F, 3, 5, 8);
		this.Shape15.setRotationPoint(3F, 4F, -9.5F);
		this.Shape15.setTextureSize(64, 32);
		this.Shape15.mirror = true;
		setRotation(this.Shape15, 0F, 0F, 0F);
		this.Shape16 = new ModelRenderer(this, 36, 0);
		this.Shape16.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape16.setRotationPoint(3.5F, 3.5F, -4F);
		this.Shape16.setTextureSize(64, 32);
		this.Shape16.mirror = true;
		setRotation(this.Shape16, 0F, 0F, 0F);
		this.Shape17 = new ModelRenderer(this, 36, 0);
		this.Shape17.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape17.setRotationPoint(3.5F, 2.7F, -3.5F);
		this.Shape17.setTextureSize(64, 32);
		this.Shape17.mirror = true;
		setRotation(this.Shape17, 0F, 0F, 0F);
		this.Shape18 = new ModelRenderer(this, 36, 0);
		this.Shape18.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape18.setRotationPoint(3.5F, 2.2F, -2.8F);
		this.Shape18.setTextureSize(64, 32);
		this.Shape18.mirror = true;
		setRotation(this.Shape18, 0F, 0F, 0F);
		this.Shape19 = new ModelRenderer(this, 36, 0);
		this.Shape19.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape19.setRotationPoint(3.5F, 1.8F, -2F);
		this.Shape19.setTextureSize(64, 32);
		this.Shape19.mirror = true;
		setRotation(this.Shape19, 0F, 0F, 0F);
		this.Shape20 = new ModelRenderer(this, 16, 9);
		this.Shape20.addBox(0F, 0F, 0F, 6, 1, 4);
		this.Shape20.setRotationPoint(7F, 4F, -2F);
		this.Shape20.setTextureSize(64, 32);
		this.Shape20.mirror = true;
		setRotation(this.Shape20, 0F, 0F, 0F);
		this.Shape21 = new ModelRenderer(this, 8, 12);
		this.Shape21.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape21.setRotationPoint(11F, 0F, 0F);
		this.Shape21.setTextureSize(64, 32);
		this.Shape21.mirror = true;
		setRotation(this.Shape21, 0F, 0F, 0F);
		this.Shape22 = new ModelRenderer(this, 8, 14);
		this.Shape22.addBox(0F, 0F, 0F, 2, 1, 2);
		this.Shape22.setRotationPoint(11F, -1F, 0F);
		this.Shape22.setTextureSize(64, 32);
		this.Shape22.mirror = true;
		setRotation(this.Shape22, -0.3490659F, 0F, 0F);
		this.Shape1 = new ModelRenderer(this, 42, 0);
		this.Shape1.addBox(0F, 0F, 0F, 3, 5, 8);
		this.Shape1.setRotationPoint(3F, 4F, 1.5F);
		this.Shape1.setTextureSize(64, 32);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 36, 0);
		this.Shape2.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape2.setRotationPoint(3.5F, 3.5F, 3F);
		this.Shape2.setTextureSize(64, 32);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 36, 0);
		this.Shape3.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape3.setRotationPoint(3.5F, 2.7F, 2.5F);
		this.Shape3.setTextureSize(64, 32);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 36, 0);
		this.Shape4.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape4.setRotationPoint(3.5F, 2.2F, 1.8F);
		this.Shape4.setTextureSize(64, 32);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape5 = new ModelRenderer(this, 36, 0);
		this.Shape5.addBox(0F, 0F, 0F, 2, 1, 1);
		this.Shape5.setRotationPoint(3.5F, 1.8F, 1F);
		this.Shape5.setTextureSize(64, 32);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 18, 17);
		this.Shape6.addBox(0F, 0F, 0F, 1, 5, 6);
		this.Shape6.setRotationPoint(-1F, 1F, -3F);
		this.Shape6.setTextureSize(64, 32);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 32, 13);
		this.Shape7.addBox(0F, 0F, 0F, 1, 4, 15);
		this.Shape7.setRotationPoint(-2F, 2F, -7.5F);
		this.Shape7.setTextureSize(64, 32);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		this.Shape16.render(f5);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		this.Shape19.render(f5);
		this.Shape20.render(f5);
		this.Shape21.render(f5);
		this.Shape22.render(f5);
		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
	}

	public void renderAll(float f5) {
        GL11.glPushMatrix();
        GL11.glTranslated(1D/16D * 2, 0, 0);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		this.Shape16.render(f5);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		this.Shape19.render(f5);
		this.Shape20.render(f5);
		this.Shape21.render(f5);
		this.Shape22.render(f5);
		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
        GL11.glPopMatrix();
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
