// Date: 14.08.2016 18:55:34
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelZOMG extends ModelBase {
	// fields
	ModelRenderer Body;
	ModelRenderer BodyFront;
	ModelRenderer BodyFrontPlate;
	ModelRenderer PipeLeft;
	ModelRenderer PipeRight;
	ModelRenderer PipeBottom;
	ModelRenderer Head;
	ModelRenderer HeadBottom;
	ModelRenderer HeadBottomPlate;
	ModelRenderer BodyTop;
	ModelRenderer BodyCenter;
	ModelRenderer BodyBack;
	ModelRenderer BodyBackPlate;
	ModelRenderer StockTop;
	ModelRenderer StockBack;
	ModelRenderer StockBackPlate;
	ModelRenderer Handle;
	ModelRenderer PistonBack;
	ModelRenderer PistonFront;
	ModelRenderer BarrelVertical;
	ModelRenderer BarrelHorizontal;
	ModelRenderer BarrelCenter;
	ModelRenderer HandleBack;
	ModelRenderer BarrelPipe;
	ModelRenderer PistonPivot;
	ModelRenderer Scope;
	ModelRenderer ScopePivot;

	public ModelZOMG() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.Body = new ModelRenderer(this, 0, 0);
		this.Body.addBox(0F, 0F, 0F, 12, 5, 4);
		this.Body.setRotationPoint(-6F, 0F, 0F);
		this.Body.setTextureSize(128, 64);
		this.Body.mirror = true;
		setRotation(this.Body, 0F, 0F, 0F);
		this.BodyFront = new ModelRenderer(this, 32, 14);
		this.BodyFront.addBox(0F, 0F, 0F, 1, 4, 4);
		this.BodyFront.setRotationPoint(-7F, 0F, 0F);
		this.BodyFront.setTextureSize(128, 64);
		this.BodyFront.mirror = true;
		setRotation(this.BodyFront, 0F, 0F, 0F);
		this.BodyFrontPlate = new ModelRenderer(this, 46, 6);
		this.BodyFrontPlate.addBox(-2F, -1F, 0F, 2, 1, 4);
		this.BodyFrontPlate.setRotationPoint(-6F, 5F, 0F);
		this.BodyFrontPlate.setTextureSize(128, 64);
		this.BodyFrontPlate.mirror = true;
		setRotation(this.BodyFrontPlate, 0F, 0F, 0.6981317F);
		this.PipeLeft = new ModelRenderer(this, 0, 29);
		this.PipeLeft.addBox(0F, 0F, 0F, 6, 1, 1);
		this.PipeLeft.setRotationPoint(-13F, 0.5F, 0.5F);
		this.PipeLeft.setTextureSize(128, 64);
		this.PipeLeft.mirror = true;
		setRotation(this.PipeLeft, 0F, 0F, 0F);
		this.PipeRight = new ModelRenderer(this, 14, 29);
		this.PipeRight.addBox(0F, 0F, 0F, 6, 1, 1);
		this.PipeRight.setRotationPoint(-13F, 0.5F, 2.5F);
		this.PipeRight.setTextureSize(128, 64);
		this.PipeRight.mirror = true;
		setRotation(this.PipeRight, 0F, 0F, 0F);
		this.PipeBottom = new ModelRenderer(this, 14, 25);
		this.PipeBottom.addBox(0F, 0F, 0F, 6, 2, 2);
		this.PipeBottom.setRotationPoint(-13F, 2F, 1F);
		this.PipeBottom.setTextureSize(128, 64);
		this.PipeBottom.mirror = true;
		setRotation(this.PipeBottom, 0F, 0F, 0F);
		this.Head = new ModelRenderer(this, 32, 0);
		this.Head.addBox(0F, 0F, 0F, 3, 4, 4);
		this.Head.setRotationPoint(-16F, 0F, 0F);
		this.Head.setTextureSize(128, 64);
		this.Head.mirror = true;
		setRotation(this.Head, 0F, 0F, 0F);
		this.HeadBottom = new ModelRenderer(this, 46, 0);
		this.HeadBottom.addBox(0F, 0F, 0F, 2, 2, 4);
		this.HeadBottom.setRotationPoint(-15F, 4F, 0F);
		this.HeadBottom.setTextureSize(128, 64);
		this.HeadBottom.mirror = true;
		setRotation(this.HeadBottom, 0F, 0F, 0F);
		this.HeadBottomPlate = new ModelRenderer(this, 32, 8);
		this.HeadBottomPlate.addBox(0F, 0F, 0F, 1, 2, 4);
		this.HeadBottomPlate.setRotationPoint(-16F, 4F, 0F);
		this.HeadBottomPlate.setTextureSize(128, 64);
		this.HeadBottomPlate.mirror = true;
		setRotation(this.HeadBottomPlate, 0F, 0F, -0.4363323F);
		this.BodyTop = new ModelRenderer(this, 0, 17);
		this.BodyTop.addBox(0F, 0F, 0F, 10, 1, 3);
		this.BodyTop.setRotationPoint(-5F, -0.5F, 0.5F);
		this.BodyTop.setTextureSize(128, 64);
		this.BodyTop.mirror = true;
		setRotation(this.BodyTop, 0F, 0F, 0F);
		this.BodyCenter = new ModelRenderer(this, 0, 9);
		this.BodyCenter.addBox(0F, 0F, 0F, 11, 3, 5);
		this.BodyCenter.setRotationPoint(-5.5F, 1F, -0.5F);
		this.BodyCenter.setTextureSize(128, 64);
		this.BodyCenter.mirror = true;
		setRotation(this.BodyCenter, 0F, 0F, 0F);
		this.BodyBack = new ModelRenderer(this, 42, 11);
		this.BodyBack.addBox(0F, 0F, 0F, 1, 3, 4);
		this.BodyBack.setRotationPoint(6F, 2F, 0F);
		this.BodyBack.setTextureSize(128, 64);
		this.BodyBack.mirror = true;
		setRotation(this.BodyBack, 0F, 0F, 0F);
		this.BodyBackPlate = new ModelRenderer(this, 58, 0);
		this.BodyBackPlate.addBox(-1F, -3F, 0F, 1, 4, 2);
		this.BodyBackPlate.setRotationPoint(7F, 2F, 1F);
		this.BodyBackPlate.setTextureSize(128, 64);
		this.BodyBackPlate.mirror = true;
		setRotation(this.BodyBackPlate, 0F, 0F, -0.4363323F);
		this.StockTop = new ModelRenderer(this, 0, 21);
		this.StockTop.addBox(0F, 0F, 0F, 8, 2, 2);
		this.StockTop.setRotationPoint(7F, 3F, 1F);
		this.StockTop.setTextureSize(128, 64);
		this.StockTop.mirror = true;
		setRotation(this.StockTop, 0F, 0F, 0F);
		this.StockBack = new ModelRenderer(this, 20, 21);
		this.StockBack.addBox(0F, 0F, 0F, 4, 2, 2);
		this.StockBack.setRotationPoint(11F, 5F, 1F);
		this.StockBack.setTextureSize(128, 64);
		this.StockBack.mirror = true;
		setRotation(this.StockBack, 0F, 0F, 0F);
		this.StockBackPlate = new ModelRenderer(this, 0, 25);
		this.StockBackPlate.addBox(-5F, -2F, 0F, 5, 2, 2);
		this.StockBackPlate.setRotationPoint(11F, 7F, 1F);
		this.StockBackPlate.setTextureSize(128, 64);
		this.StockBackPlate.mirror = true;
		setRotation(this.StockBackPlate, 0F, 0F, 0.418879F);
		this.Handle = new ModelRenderer(this, 64, 8);
		this.Handle.addBox(0F, 0F, 0F, 2, 4, 2);
		this.Handle.setRotationPoint(-4F, 5F, 1F);
		this.Handle.setTextureSize(128, 64);
		this.Handle.mirror = true;
		setRotation(this.Handle, 0F, 0F, 0F);
		this.PistonBack = new ModelRenderer(this, 30, 26);
		this.PistonBack.addBox(0F, -4F, 0F, 2, 4, 2);
		this.PistonBack.setRotationPoint(1F, 4F, -0.5F);
		this.PistonBack.setTextureSize(128, 64);
		this.PistonBack.mirror = true;
		setRotation(this.PistonBack, 0.7853982F, 0F, 0F);
		this.PistonFront = new ModelRenderer(this, 52, 11);
		this.PistonFront.addBox(0F, -4F, 0F, 2, 4, 2);
		this.PistonFront.setRotationPoint(-3F, 4F, -0.5F);
		this.PistonFront.setTextureSize(128, 64);
		this.PistonFront.mirror = true;
		setRotation(this.PistonFront, 0.7853982F, 0F, 0F);
		this.BarrelVertical = new ModelRenderer(this, 38, 22);
		this.BarrelVertical.addBox(0F, 0F, 0F, 8, 3, 2);
		this.BarrelVertical.setRotationPoint(-4F, 1F, 5F);
		this.BarrelVertical.setTextureSize(128, 64);
		this.BarrelVertical.mirror = true;
		setRotation(this.BarrelVertical, 0F, 0F, 0F);
		this.BarrelHorizontal = new ModelRenderer(this, 38, 27);
		this.BarrelHorizontal.addBox(0F, 0F, 0F, 8, 2, 3);
		this.BarrelHorizontal.setRotationPoint(-4F, 1.5F, 4.5F);
		this.BarrelHorizontal.setTextureSize(128, 64);
		this.BarrelHorizontal.mirror = true;
		setRotation(this.BarrelHorizontal, 0F, 0F, 0F);
		this.BarrelCenter = new ModelRenderer(this, 64, 0);
		this.BarrelCenter.addBox(0F, 0F, 0F, 10, 2, 2);
		this.BarrelCenter.setRotationPoint(-5F, 1.5F, 5F);
		this.BarrelCenter.setTextureSize(128, 64);
		this.BarrelCenter.mirror = true;
		setRotation(this.BarrelCenter, 0F, 0F, 0F);
		this.HandleBack = new ModelRenderer(this, 60, 8);
		this.HandleBack.addBox(0F, 0F, 0F, 1, 4, 1);
		this.HandleBack.setRotationPoint(-2.5F, 5F, 1.5F);
		this.HandleBack.setTextureSize(128, 64);
		this.HandleBack.mirror = true;
		setRotation(this.HandleBack, 0F, 0F, 0F);
		this.BarrelPipe = new ModelRenderer(this, 64, 4);
		this.BarrelPipe.addBox(-10F, 0F, -1F, 10, 1, 1);
		this.BarrelPipe.setRotationPoint(-5F, 2F, 6.5F);
		this.BarrelPipe.setTextureSize(128, 64);
		this.BarrelPipe.mirror = true;
		setRotation(this.BarrelPipe, 0F, -0.2602503F, 0F);
		this.PistonPivot = new ModelRenderer(this, 60, 14);
		this.PistonPivot.addBox(0F, -2F, 0.5F, 7, 2, 1);
		this.PistonPivot.setRotationPoint(-3.5F, 4F, -0.5F);
		this.PistonPivot.setTextureSize(128, 64);
		this.PistonPivot.mirror = true;
		setRotation(this.PistonPivot, 0.7853982F, 0F, 0F);
		this.Scope = new ModelRenderer(this, 48, 18);
		this.Scope.addBox(0F, 0F, 0F, 6, 2, 2);
		this.Scope.setRotationPoint(-3F, -3F, 1F);
		this.Scope.setTextureSize(128, 64);
		this.Scope.mirror = true;
		setRotation(this.Scope, 0F, 0F, 0F);
		this.ScopePivot = new ModelRenderer(this, 58, 6);
		this.ScopePivot.addBox(0F, 0F, 0F, 4, 1, 1);
		this.ScopePivot.setRotationPoint(-2F, -1F, 1.5F);
		this.ScopePivot.setTextureSize(128, 64);
		this.ScopePivot.mirror = true;
		setRotation(this.ScopePivot, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Body.render(f5);
		this.BodyFront.render(f5);
		this.BodyFrontPlate.render(f5);
		this.PipeLeft.render(f5);
		this.PipeRight.render(f5);
		this.PipeBottom.render(f5);
		this.Head.render(f5);
		this.HeadBottom.render(f5);
		this.HeadBottomPlate.render(f5);
		this.BodyTop.render(f5);
		this.BodyCenter.render(f5);
		this.BodyBack.render(f5);
		this.BodyBackPlate.render(f5);
		this.StockTop.render(f5);
		this.StockBack.render(f5);
		this.StockBackPlate.render(f5);
		this.Handle.render(f5);
		this.PistonBack.render(f5);
		this.PistonFront.render(f5);
		this.BarrelVertical.render(f5);
		this.BarrelHorizontal.render(f5);
		this.BarrelCenter.render(f5);
		this.HandleBack.render(f5);
		this.BarrelPipe.render(f5);
		this.PistonPivot.render(f5);
		this.Scope.render(f5);
		this.ScopePivot.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
