// Date: 04.10.2015 21:16:44
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPoleTop extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
  
  public ModelPoleTop()
  {
    this.textureWidth = 64;
    this.textureHeight = 64;
    
      this.Shape1 = new ModelRenderer(this, 0, 1);
      this.Shape1.addBox(0F, 0F, 0F, 12, 8, 12);
      this.Shape1.setRotationPoint(-6F, 16F, -6F);
      this.Shape1.setTextureSize(64, 64);
      this.Shape1.mirror = true;
      setRotation(this.Shape1, 0F, 0F, 0F);
      this.Shape2 = new ModelRenderer(this, 0, 23);
      this.Shape2.addBox(0F, 0F, 0F, 4, 16, 4);
      this.Shape2.setRotationPoint(4F, 4F, -8F);
      this.Shape2.setTextureSize(64, 64);
      this.Shape2.mirror = true;
      setRotation(this.Shape2, 0F, 0F, 0F);
      this.Shape3 = new ModelRenderer(this, 0, 23);
      this.Shape3.addBox(0F, 0F, 0F, 4, 16, 4);
      this.Shape3.setRotationPoint(4F, 4F, 4F);
      this.Shape3.setTextureSize(64, 64);
      this.Shape3.mirror = true;
      setRotation(this.Shape3, 0F, 0F, 0F);
      this.Shape4 = new ModelRenderer(this, 0, 23);
      this.Shape4.addBox(0F, 0F, 0F, 4, 16, 4);
      this.Shape4.setRotationPoint(-8F, 4F, -8F);
      this.Shape4.setTextureSize(64, 64);
      this.Shape4.mirror = true;
      setRotation(this.Shape4, 0F, 0F, 0F);
      this.Shape5 = new ModelRenderer(this, 0, 23);
      this.Shape5.addBox(0F, 0F, 0F, 4, 16, 4);
      this.Shape5.setRotationPoint(-8F, 4F, 4F);
      this.Shape5.setTextureSize(64, 64);
      this.Shape5.mirror = true;
      setRotation(this.Shape5, 0F, 0F, 0F);
      this.Shape6 = new ModelRenderer(this, 0, 47);
      this.Shape6.addBox(0F, 0F, 0F, 4, 2, 4);
      this.Shape6.setRotationPoint(-2F, 14F, -2F);
      this.Shape6.setTextureSize(64, 64);
      this.Shape6.mirror = true;
      setRotation(this.Shape6, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.Shape1.render(f5);
    this.Shape2.render(f5);
    this.Shape3.render(f5);
    this.Shape4.render(f5);
    this.Shape5.render(f5);
    this.Shape6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void renderModel(float f)
  {
	    this.Shape1.render(f);
	    this.Shape2.render(f);
	    this.Shape3.render(f);
	    this.Shape4.render(f);
	    this.Shape5.render(f);
	    this.Shape6.render(f);
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
