// Date: 21.02.2017 20:44:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;

public class ModelHP extends ModelBase
{
  //fields
    ModelRenderer Printer;
    ModelRenderer Hatch;
    ModelRenderer Display;
    ModelRenderer Stock;
    ModelRenderer StockBottom;
    ModelRenderer StockPlate;
    ModelRenderer Barrel;
    ModelRenderer Lens1;
    ModelRenderer Lens2;
    ModelRenderer Lens3;
    ModelRenderer Beam;
    ModelRenderer Handle;
    ModelRenderer Dot;
    ModelRenderer Back;
    ModelRenderer BackShaft;
    ModelRenderer Muzzle;
    ModelRenderer BarrelPlate;
  
  public ModelHP()
  {
    this.textureWidth = 64;
    this.textureHeight = 64;
    
      this.Printer = new ModelRenderer(this, 0, 0);
      this.Printer.addBox(0F, 0F, 0F, 12, 9, 6);
      this.Printer.setRotationPoint(-6F, -3F, -3F);
      this.Printer.setTextureSize(64, 64);
      this.Printer.mirror = true;
      setRotation(this.Printer, 0F, 0F, 0F);
      this.Hatch = new ModelRenderer(this, 0, 15);
      this.Hatch.addBox(0F, 0F, 0F, 6, 5, 1);
      this.Hatch.setRotationPoint(-3F, -1F, -3F);
      this.Hatch.setTextureSize(64, 64);
      this.Hatch.mirror = true;
      setRotation(this.Hatch, 0F, 0F, 0F);
      this.Display = new ModelRenderer(this, 14, 15);
      this.Display.addBox(0F, -2F, 0F, 2, 2, 1);
      this.Display.setRotationPoint(3.5F, 0F, -3F);
      this.Display.setTextureSize(64, 64);
      this.Display.mirror = true;
      setRotation(this.Display, 0.7853982F, 0F, 0F);
      this.Stock = new ModelRenderer(this, 0, 21);
      this.Stock.addBox(0F, 0F, 0F, 12, 3, 2);
      this.Stock.setRotationPoint(6F, 0F, -1F);
      this.Stock.setTextureSize(64, 64);
      this.Stock.mirror = true;
      setRotation(this.Stock, 0F, 0F, 0F);
      this.StockBottom = new ModelRenderer(this, 20, 15);
      this.StockBottom.addBox(0F, 0F, 0F, 3, 3, 2);
      this.StockBottom.setRotationPoint(15F, 3F, -1F);
      this.StockBottom.setTextureSize(64, 64);
      this.StockBottom.mirror = true;
      setRotation(this.StockBottom, 0F, 0F, 0F);
      this.StockPlate = new ModelRenderer(this, 0, 26);
      this.StockPlate.addBox(-8F, -3F, 0F, 8, 3, 2);
      this.StockPlate.setRotationPoint(15F, 6F, -1F);
      this.StockPlate.setTextureSize(64, 64);
      this.StockPlate.mirror = true;
      setRotation(this.StockPlate, 0F, 0F, 0.3839724F);
      this.Barrel = new ModelRenderer(this, 0, 31);
      this.Barrel.addBox(0F, 0F, 0F, 15, 2, 2);
      this.Barrel.setRotationPoint(-21F, 0F, -1F);
      this.Barrel.setTextureSize(64, 64);
      this.Barrel.mirror = true;
      setRotation(this.Barrel, 0F, 0F, 0F);
      this.Lens1 = new ModelRenderer(this, 0, 35);
      this.Lens1.addBox(0F, 0F, 0F, 1, 3, 3);
      this.Lens1.setRotationPoint(-19F, -3F, -1.5F);
      this.Lens1.setTextureSize(64, 64);
      this.Lens1.mirror = true;
      setRotation(this.Lens1, 0F, 0F, 0F);
      this.Lens2 = new ModelRenderer(this, 8, 35);
      this.Lens2.addBox(0F, 0F, 0F, 1, 4, 4);
      this.Lens2.setRotationPoint(-16F, -3.5F, -2F);
      this.Lens2.setTextureSize(64, 64);
      this.Lens2.mirror = true;
      setRotation(this.Lens2, 0F, 0F, 0F);
      this.Lens3 = new ModelRenderer(this, 0, 41);
      this.Lens3.addBox(0F, 0F, 0F, 1, 3, 3);
      this.Lens3.setRotationPoint(-13F, -3F, -1.466667F);
      this.Lens3.setTextureSize(64, 64);
      this.Lens3.mirror = true;
      setRotation(this.Lens3, 0F, 0F, 0F);
      this.Beam = new ModelRenderer(this, 0, 47);
      this.Beam.addBox(0F, 0F, 0F, 12, 1, 1);
      this.Beam.setRotationPoint(-18F, -2F, -0.5F);
      this.Beam.setTextureSize(64, 64);
      this.Beam.mirror = true;
      setRotation(this.Beam, 0F, 0F, 0F);
      this.Handle = new ModelRenderer(this, 18, 35);
      this.Handle.addBox(0F, 0F, 0F, 2, 6, 1);
      this.Handle.setRotationPoint(-16F, 2F, -0.5F);
      this.Handle.setTextureSize(64, 64);
      this.Handle.mirror = true;
      setRotation(this.Handle, 0F, 0F, -0.1745329F);
      this.Dot = new ModelRenderer(this, 0, 49);
      this.Dot.addBox(0F, 0F, 0F, 2, 1, 1);
      this.Dot.setRotationPoint(-20F, 2F, -0.5F);
      this.Dot.setTextureSize(64, 64);
      this.Dot.mirror = true;
      setRotation(this.Dot, 0F, 0F, 0F);
      this.Back = new ModelRenderer(this, 0, 51);
      this.Back.addBox(-1F, -3F, 0F, 1, 3, 2);
      this.Back.setRotationPoint(7F, 0F, -1F);
      this.Back.setTextureSize(64, 64);
      this.Back.mirror = true;
      setRotation(this.Back, 0F, 0F, -0.3490659F);
      this.BackShaft = new ModelRenderer(this, 0, 56);
      this.BackShaft.addBox(0F, 0F, 0F, 4, 1, 1);
      this.BackShaft.setRotationPoint(6F, -1F, -0.5F);
      this.BackShaft.setTextureSize(64, 64);
      this.BackShaft.mirror = true;
      setRotation(this.BackShaft, 0F, 0F, 0F);
      this.Muzzle = new ModelRenderer(this, 0, 58);
      this.Muzzle.addBox(0F, 0F, 0F, 1, 2, 2);
      this.Muzzle.setRotationPoint(-6.5F, -2.5F, -1F);
      this.Muzzle.setTextureSize(64, 64);
      this.Muzzle.mirror = true;
      setRotation(this.Muzzle, 0F, 0F, 0F);
      this.BarrelPlate = new ModelRenderer(this, 6, 58);
      this.BarrelPlate.addBox(-4F, -2F, 0F, 4, 2, 1);
      this.BarrelPlate.setRotationPoint(-6F, 4F, -0.5F);
      this.BarrelPlate.setTextureSize(64, 64);
      this.BarrelPlate.mirror = true;
      setRotation(this.BarrelPlate, 0F, 0F, 0.5235988F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.Printer.render(f5);
    GL11.glDisable(GL11.GL_CULL_FACE);
    this.Hatch.render(f5);
    GL11.glEnable(GL11.GL_CULL_FACE);
    this.Display.render(f5);
    this.Stock.render(f5);
    this.StockBottom.render(f5);
    this.StockPlate.render(f5);
    this.Barrel.render(f5);
    GL11.glEnable(GL11.GL_BLEND);
    //GL11.glDisable(GL11.GL_ALPHA_TEST);
    OpenGlHelper.glBlendFunc(770, 771, 1, 0);
    this.Lens1.render(f5);
    this.Lens2.render(f5);
    this.Lens3.render(f5);
    this.Beam.render(f5);
	GL11.glDisable(GL11.GL_BLEND);
    this.Handle.render(f5);
    this.Dot.render(f5);
    this.Back.render(f5);
    this.BackShaft.render(f5);
    this.Muzzle.render(f5);
    this.BarrelPlate.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
