// Date: 29.08.2016 09:41:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOSIPR extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;

	public ModelOSIPR() {
		this.textureWidth = 64;
		this.textureHeight = 64;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 8, 3, 3);
		this.Shape1.setRotationPoint(0F, 0F, -0.5F);
		this.Shape1.setTextureSize(64, 64);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 6);
		this.Shape2.addBox(0F, 0F, 0F, 11, 2, 2);
		this.Shape2.setRotationPoint(8F, 0F, 0F);
		this.Shape2.setTextureSize(64, 64);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 10);
		this.Shape3.addBox(0F, 0F, 0F, 2, 3, 2);
		this.Shape3.setRotationPoint(17F, 2F, 0F);
		this.Shape3.setTextureSize(64, 64);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 0, 15);
		this.Shape4.addBox(-5F, -3F, 0F, 5, 3, 2);
		this.Shape4.setRotationPoint(17F, 5F, 0F);
		this.Shape4.setTextureSize(64, 64);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0.4363323F);
		this.Shape5 = new ModelRenderer(this, 8, 10);
		this.Shape5.addBox(-8F, -1F, 0F, 3, 1, 2);
		this.Shape5.setRotationPoint(17F, 5F, 0F);
		this.Shape5.setTextureSize(64, 64);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0.4363323F);
		this.Shape6 = new ModelRenderer(this, 30, 0);
		this.Shape6.addBox(0F, 0F, 0F, 10, 2, 2);
		this.Shape6.setRotationPoint(-10F, 0.5F, 0F);
		this.Shape6.setTextureSize(64, 64);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 54, 0);
		this.Shape7.addBox(0F, 0F, 0F, 3, 2, 1);
		this.Shape7.setRotationPoint(-13F, 0.5F, 0.5F);
		this.Shape7.setTextureSize(64, 64);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0F);
		this.Shape8 = new ModelRenderer(this, 30, 4);
		this.Shape8.addBox(0F, 0F, 0F, 10, 3, 3);
		this.Shape8.setRotationPoint(-16F, 2F, -0.5F);
		this.Shape8.setTextureSize(64, 64);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
		this.Shape9 = new ModelRenderer(this, 30, 10);
		this.Shape9.addBox(0F, 0F, 0F, 3, 1, 3);
		this.Shape9.setRotationPoint(-19F, 4F, -0.5F);
		this.Shape9.setTextureSize(64, 64);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, 0F, 0F);
		this.Shape10 = new ModelRenderer(this, 42, 10);
		this.Shape10.addBox(0F, 0F, 0F, 3, 1, 3);
		this.Shape10.setRotationPoint(-19F, 2F, -0.5F);
		this.Shape10.setTextureSize(64, 64);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, 0F, 0F, 0F);
		this.Shape11 = new ModelRenderer(this, 0, 20);
		this.Shape11.addBox(0F, 0F, 0F, 1, 1, 2);
		this.Shape11.setRotationPoint(8F, -1F, 0F);
		this.Shape11.setTextureSize(64, 64);
		this.Shape11.mirror = true;
		setRotation(this.Shape11, 0F, 0F, 0F);
		this.Shape12 = new ModelRenderer(this, 30, 14);
		this.Shape12.addBox(0F, 0F, 0F, 7, 3, 2);
		this.Shape12.setRotationPoint(0F, 3F, 0F);
		this.Shape12.setTextureSize(64, 64);
		this.Shape12.mirror = true;
		setRotation(this.Shape12, 0F, 0F, 0F);
		this.Shape13 = new ModelRenderer(this, 30, 19);
		this.Shape13.addBox(0F, -2F, 0F, 5, 2, 2);
		this.Shape13.setRotationPoint(7F, 6F, 0F);
		this.Shape13.setTextureSize(64, 64);
		this.Shape13.mirror = true;
		setRotation(this.Shape13, 0F, 0F, -0.9599311F);
		this.Shape14 = new ModelRenderer(this, 30, 23);
		this.Shape14.addBox(0F, 0F, 0F, 2, 5, 1);
		this.Shape14.setRotationPoint(5F, 6F, 0.5F);
		this.Shape14.setTextureSize(64, 64);
		this.Shape14.mirror = true;
		setRotation(this.Shape14, 0F, 0F, -0.3490659F);
		this.Shape15 = new ModelRenderer(this, 0, 23);
		this.Shape15.addBox(0F, 0F, 0F, 7, 2, 1);
		this.Shape15.setRotationPoint(-6F, 5F, 0.5F);
		this.Shape15.setTextureSize(64, 64);
		this.Shape15.mirror = true;
		setRotation(this.Shape15, 0F, 0F, 0F);
		this.Shape16 = new ModelRenderer(this, 0, 26);
		this.Shape16.addBox(0F, 0F, 0F, 8, 1, 2);
		this.Shape16.setRotationPoint(-6F, 7F, 0F);
		this.Shape16.setTextureSize(64, 64);
		this.Shape16.mirror = true;
		setRotation(this.Shape16, 0F, 0F, 0F);
		this.Shape17 = new ModelRenderer(this, 0, 29);
		this.Shape17.addBox(0F, 0F, 0F, 3, 6, 6);
		this.Shape17.setRotationPoint(-9F, 9F, -3F);
		this.Shape17.setTextureSize(64, 64);
		this.Shape17.mirror = true;
		setRotation(this.Shape17, 0.6108652F, 0F, 0F);
		this.Shape18 = new ModelRenderer(this, 0, 41);
		this.Shape18.addBox(0F, 0F, 0F, 3, 6, 7);
		this.Shape18.setRotationPoint(-9F, 8F, -4F);
		this.Shape18.setTextureSize(64, 64);
		this.Shape18.mirror = true;
		setRotation(this.Shape18, 0F, 0F, 0F);
		this.Shape19 = new ModelRenderer(this, 30, 29);
		this.Shape19.addBox(0F, 1F, 6F, 2, 4, 3);
		this.Shape19.setRotationPoint(-8.5F, 9F, -3F);
		this.Shape19.setTextureSize(64, 64);
		this.Shape19.mirror = true;
		setRotation(this.Shape19, 0.6108652F, 0F, 0F);
		this.Shape20 = new ModelRenderer(this, 30, 36);
		this.Shape20.addBox(0F, 0F, 0F, 1, 6, 3);
		this.Shape20.setRotationPoint(-8F, 1F, 3F);
		this.Shape20.setTextureSize(64, 64);
		this.Shape20.mirror = true;
		setRotation(this.Shape20, 0F, 0F, 0F);
		this.Shape21 = new ModelRenderer(this, 30, 45);
		this.Shape21.addBox(0F, -3F, 0F, 1, 5, 4);
		this.Shape21.setRotationPoint(-8F, 2F, 3F);
		this.Shape21.setTextureSize(64, 64);
		this.Shape21.mirror = true;
		setRotation(this.Shape21, 0.9599311F, 0F, 0F);
		this.Shape22 = new ModelRenderer(this, 0, 54);
		this.Shape22.addBox(0F, 0F, 0F, 2, 2, 2);
		this.Shape22.setRotationPoint(-11F, 7F, 0F);
		this.Shape22.setTextureSize(64, 64);
		this.Shape22.mirror = true;
		setRotation(this.Shape22, 0F, 0F, 0F);
		this.Shape23 = new ModelRenderer(this, 0, 58);
		this.Shape23.addBox(-7F, -2F, 0F, 7, 2, 2);
		this.Shape23.setRotationPoint(-11F, 9F, 0F);
		this.Shape23.setTextureSize(64, 64);
		this.Shape23.mirror = true;
		setRotation(this.Shape23, 0F, 0F, 0.148353F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		this.Shape16.render(f5);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		this.Shape19.render(f5);
		this.Shape20.render(f5);
		this.Shape21.render(f5);
		this.Shape22.render(f5);
		this.Shape23.render(f5);
	}

	public void renderAll(float f5) {
		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
		this.Shape9.render(f5);
		this.Shape10.render(f5);
		this.Shape11.render(f5);
		this.Shape12.render(f5);
		this.Shape13.render(f5);
		this.Shape14.render(f5);
		this.Shape15.render(f5);
		this.Shape16.render(f5);
		this.Shape17.render(f5);
		this.Shape18.render(f5);
		this.Shape19.render(f5);
		this.Shape20.render(f5);
		this.Shape21.render(f5);
		this.Shape22.render(f5);
		this.Shape23.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
