// Date: 14.02.2017 18:33:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelJack extends ModelBase
{
  //fields
    ModelRenderer BarrelBR;
    ModelRenderer BarrelBL;
    ModelRenderer BarrelTR;
    ModelRenderer BarrelTL;
    ModelRenderer Body;
    ModelRenderer Back;
    ModelRenderer Plate;
    ModelRenderer StockMain;
    ModelRenderer StockBottom;
    ModelRenderer StockPlate;
  
  public ModelJack()
  {
    this.textureWidth = 64;
    this.textureHeight = 64;
    
      this.BarrelBR = new ModelRenderer(this, 0, 6);
      this.BarrelBR.addBox(0F, 0F, 0F, 21, 3, 3);
      this.BarrelBR.setRotationPoint(-18F, 0F, 0.2F);
      this.BarrelBR.setTextureSize(64, 64);
      this.BarrelBR.mirror = true;
      setRotation(this.BarrelBR, 0F, 0F, 0F);
      this.BarrelBL = new ModelRenderer(this, 0, 0);
      this.BarrelBL.addBox(0F, 0F, 0F, 21, 3, 3);
      this.BarrelBL.setRotationPoint(-18F, 0F, -3.2F);
      this.BarrelBL.setTextureSize(64, 64);
      this.BarrelBL.mirror = true;
      setRotation(this.BarrelBL, 0F, 0F, 0F);
      this.BarrelTR = new ModelRenderer(this, 0, 12);
      this.BarrelTR.addBox(0F, 0F, 0F, 21, 3, 3);
      this.BarrelTR.setRotationPoint(-18F, -3.2F, 0.2F);
      this.BarrelTR.setTextureSize(64, 64);
      this.BarrelTR.mirror = true;
      setRotation(this.BarrelTR, 0F, 0F, 0F);
      this.BarrelTL = new ModelRenderer(this, 0, 18);
      this.BarrelTL.addBox(0F, 0F, 0F, 21, 3, 3);
      this.BarrelTL.setRotationPoint(-18F, -3.2F, -3.2F);
      this.BarrelTL.setTextureSize(64, 64);
      this.BarrelTL.mirror = true;
      setRotation(this.BarrelTL, 0F, 0F, 0F);
      this.Body = new ModelRenderer(this, 0, 24);
      this.Body.addBox(0F, 0F, 0F, 15, 7, 4);
      this.Body.setRotationPoint(-9F, -2F, -2F);
      this.Body.setTextureSize(64, 64);
      this.Body.mirror = true;
      setRotation(this.Body, 0F, 0F, 0F);
      this.Back = new ModelRenderer(this, 38, 24);
      this.Back.addBox(0F, 0F, 0F, 3, 5, 3);
      this.Back.setRotationPoint(6F, 0F, -1.5F);
      this.Back.setTextureSize(64, 64);
      this.Back.mirror = true;
      setRotation(this.Back, 0F, 0F, 0F);
      this.Plate = new ModelRenderer(this, 0, 35);
      this.Plate.addBox(0F, 0F, 0F, 4, 2, 3);
      this.Plate.setRotationPoint(6F, -2F, -1.5F);
      this.Plate.setTextureSize(64, 64);
      this.Plate.mirror = true;
      setRotation(this.Plate, 0F, 0F, 0.4363323F);
      this.StockMain = new ModelRenderer(this, 0, 40);
      this.StockMain.addBox(0F, 0F, 0F, 13, 3, 3);
      this.StockMain.setRotationPoint(9F, 2F, -1.5F);
      this.StockMain.setTextureSize(64, 64);
      this.StockMain.mirror = true;
      setRotation(this.StockMain, 0F, 0F, 0F);
      this.StockBottom = new ModelRenderer(this, 0, 46);
      this.StockBottom.addBox(0F, 0F, 0F, 6, 3, 3);
      this.StockBottom.setRotationPoint(16F, 5F, -1.5F);
      this.StockBottom.setTextureSize(64, 64);
      this.StockBottom.mirror = true;
      setRotation(this.StockBottom, 0F, 0F, 0F);
      this.StockPlate = new ModelRenderer(this, 18, 46);
      this.StockPlate.addBox(-8F, -3F, 0F, 8, 3, 3);
      this.StockPlate.setRotationPoint(16F, 8F, -1.5F);
      this.StockPlate.setTextureSize(64, 64);
      this.StockPlate.mirror = true;
      setRotation(this.StockPlate, 0F, 0F, 0.4014257F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.BarrelBR.render(f5);
    this.BarrelBL.render(f5);
    this.BarrelTR.render(f5);
    this.BarrelTL.render(f5);
    this.Body.render(f5);
    this.Back.render(f5);
    this.Plate.render(f5);
    this.StockMain.render(f5);
    this.StockBottom.render(f5);
    this.StockPlate.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
